add_newline = false

format = """
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$nodejs\
$python\
$cmd_duration\
$time\
$status\
$jobs\
$line_break\
$character"""

[directory]
fish_style_pwd_dir_length = 2

[status]
format = '[ $status( $signal_name) ]($style) '
disabled = false
style = 'fg:white bg:red bold'

[git_branch]
symbol = ""

[git_status]
disabled = true

[python]
format = 'via [${pyenv_prefix}(${version} )(\($virtualenv\))]($style) '

[time]
disabled = false
use_12hr = true
time_format = '%I:%M %P'
