add_newline = false

format = """$shlvl\
$directory\
$git_branch\
${custom.git_host}\
$git_commit\
$git_state\
$nodejs\
$python\
$time\
$cmd_duration\
$status\
$line_break\
${custom.venv}\
$jobs\
$character"""

[directory]
fish_style_pwd_dir_length = 2

[status]
format = '[ $status( $signal_name) ]($style) '
disabled = false
style = 'fg:white bg:red bold'

[git_branch]
symbol = " "

[git_status]
disabled = true

[python]
disabled = true
format = 'via [${pyenv_prefix}(${version} )(\($virtualenv\))]($style) '

[nodejs]
symbol = ''

[time]
disabled = false
use_12hr = true
time_format = '%I:%M %P'

[custom.venv]
shell = ['dash']
command = """
if [ "${VIRTUAL_ENV%%/src/.venv*}" != "$VIRTUAL_ENV" ]; then
  basename "${VIRTUAL_ENV%/*/*}"
else
  echo "${VIRTUAL_ENV#${VIRTUAL_ENV%/*/*}/}"
fi
"""
when = 'test -n "$VIRTUAL_ENV"'
format = '([\($output\)]($style) )'
style = 'fg:242'
description = 'Custom formatted python virtual environment name'

[custom.git_host]
shell = ['dash']
command = "command git ls-remote --get-url"
when = "command git rev-parse --is-inside-work-tree"
format = "at [$output]($style) "
disabled = true

[jobs]
threshold = 0
symbol = '+'
format = '([$symbol$number]($style) )'
style = 'fg:red bold'
