#!/usr/bin/env zsh

local venv="$1"
if [[ -z "$venv" ]] || [[ ! -f "$venv/bin/activate" ]]; then
  echo "You have to pass a virtual environment path." >&2
  return 1
fi

if [[ -n "$VIRTUAL_ENV" ]] && [[ "$VIRTUAL_ENV" = "$venv" ]]; then
  # Already in venv
  return
fi

if [[ -n "$VIRTUAL_ENV" ]]; then
  # In a different virtual_env
  save_virtual_env
fi

echo_run source "$venv/bin/activate"
