#!/usr/bin/env zsh

local cmd="git"
if ! in_git_repo; then
  echo "Not in a git repository. Using yadm."
  cmd="yadm"
fi

if [[ "$#" -eq 0 ]] && [[ "$cmd" != "yadm" ]]; then
  local rel_path="$(realpath --relative-to="$PWD" "$(git rev-parse --show-toplevel)")"
  echo_run git add --verbose "$rel_path"
  status
  return $?
elif [[ "$#" -eq 0 ]] && [[ "$cmd" = "yadm" ]]; then
  echo_run yadm add --update --verbose
  echo_run yadm status
  return $?
fi

echo_run $cmd add --verbose "$@"
status
