#!/usr/bin/env zsh

(
local tf_dir="$HOME/Code/infra/terraform"

echo_run cd "$tf_dir"
echo_run terraform fmt
echo_run yadm encrypt
echo_run yadm add .
echo_run yadm add "$HOME/.config/yadm/files.gpg"
)
