#!/usr/bin/env zsh

local cmd="git"
if ! in_git_repo; then
  echo "Not in git repository. Using yadm."
  cmd="yadm"
fi

if is_clean_repo $cmd; then
  echo "There are no changes to be amended."
  return 1
fi

add || return $?

echo "Use '$cmd reset $(git rev-parse HEAD)' if you want to un-amend."
echo_run $cmd commit --amend --no-edit "$@"
