#!/usr/bin/env zsh

if [[ -z "$1" ]]; then
  echo "Usage: $0 PACKAGE"
  return 1
fi

( # Enter a sub-shell to cd without worrying

set -e

echo_run mkdir -p "$HOME/.cache/aur"
echo_run cd "$HOME/.cache/aur"
echo_run git clone "https://aur.archlinux.org/$1.git" "$1" || true
echo_run cd "$1"
echo_run git pull --rebase
echo -n "${fg[yellow]}Want to read the PKGBUILD? (Y/n)?${reset_color} "
local reply
read reply
if ! [[ "$reply" != "${reply#[Nn]}" ]]; then
  echo_run less PKGBUILD
fi
safe_run makepkg --syncdeps --noconfirm --install --clean || echo "Failed to install"

)
