#!/usr/bin/env zsh

# https://github.com/SidOfc/dotfiles/blob/d07fa3862ed065c2a5a7f1160ae98416bfe2e1ee/zsh/bip
### BREW + FZF
# update multiple packages at once
# mnemonic [B]rew [U]pdate [P]lugin

local inst=$(brew search | eval "fzf ${FZF_DEFAULT_OPTS} --multi --header='[brew:install]'")

if [[ $inst ]]; then
  for prog in $(echo $inst); do
    echo-run brew install $prog
  done
fi
