#!/usr/bin/env zsh

if [[ "$VIRTUAL_ENV" != "" ]]; then
  echo -n "${fg[red]}"
  echo "Warning:${reset_color} It's dangerous to run brew from within a virtual environment."
  echo "         See https://docs.brew.sh/Homebrew-and-Python for more info."
  return 1
fi

command brew $@
