#!/usr/bin/env zsh

# https://github.com/SidOfc/dotfiles/blob/d07fa3862ed065c2a5a7f1160ae98416bfe2e1ee/zsh/bup
### BREW + FZF
# uninstall multiple packages at once, async
# mnemonic [B]rew [C]lean [P]lugin (e.g. uninstall)

local upd=$(brew leaves | eval "fzf ${FZF_DEFAULT_OPTS} --multi --header='[brew:update]'")

if [[ $upd ]]; then
  for prog in $(echo $upd); do
    echo-run brew upgrade $prog
  done
fi
