#!/usr/bin/env zsh

local current_branch=$(git rev-parse --abbrev-ref HEAD)
local branch
for branch in $(git for-each-ref --sort=committerdate refs/heads --format='%(refname:short)'); do
  if [ "$branch" = "develop" ] || [ "$branch" = "master" ] || [ "$branch" = "$current_branch" ]; then
    continue
  fi

  git_show --quiet "$branch"
  safe_run git branch -D "$branch"
  if [[ "$status" -ne 0 ]]; then
    echo "Not deleting..."
  fi

  echo
done
