#!/usr/bin/env zsh

local tag="$1"

if [[ -z "$tag" ]]; then
  echo "Usage: $0 TAG"
  return 1
fi

if ! in_git_repo; then
  echo_err "Not in git repository."
  return 128
fi

echo_run git fetch --tags --force --prune --quiet || return "$status"

echo_run git tag -d "$tag" || return "$status"
safe_run git push origin ":refs/tags/$tag" || return "$status"
