#!/usr/bin/env zsh

local remote_branches=($(
  git for-each-ref --sort=committerdate refs/remotes/origin \
    --format='%(authoremail) %(refname)' \
    | grep -E '(george\.witteman@affirm\.com|george@witteman\.me)' \
    | grep origin \
    | cut -d ' ' -f 2))

local branches=(${(M)remote_branches/#refs\/remotes\/origin\//})

local branch
for branch in $branches; do
  if [ "$branch" = "develop" ] || [ "$branch" = "master" ] || [ "$branch" = "$current_branch" ]; then
    continue
  fi

  git-show --quiet "refs/remotes/origin/$branch"
  safe-run git push origin --delete "$branch"
  if [[ "$status" -ne 0 ]]; then
    echo "Not deleting..."
  fi

  echo
done
