#!/usr/bin/env zsh

local end_time="$EPOCHREALTIME"
local elapsed=$((($end_time * 1000) - ($_PROF_START_TIME * 1000)))
autoload -U colors && colors

echo -n "${bold_color}${_PROF_COMMAND}${reset_color} took "
echo "${bold_color}${elapsed[0,8]}ms${reset_color}"
