#!/usr/bin/env zsh

local end_time="$EPOCHREALTIME"
local run_count="${1:-1}"
local elapsed_ms=(${(ps:.:)$(( ( $end_time * 1000 - $_PROF_START_TIME * 1000 ) / $run_count ))})
# local elapsed=$(( (($end_time * 1000) - ($_PROF_START_TIME * 1000)) / $run_count))
autoload -U colors && colors

if [[ -n "${_PROF_COMMAND}" ]]; then
  echo -n "${bold_color}${_PROF_COMMAND}${reset_color} took "
else
  echo -n "The command took "
fi
echo -n "${bold_color}${elapsed_ms[1]}.${${elapsed_ms[2]}[1,5]}ms${reset_color} "
if [[ $run_count -eq 1 ]]; then
  echo "for all runs"
else
  echo "per run (for $run_count runs)"
fi
unset _PROF_COMMAND
