#!/usr/bin/env zsh

local cmd="git"
if ! in_git_repo; then
  echo_info "Not in git repository. Using yadm."
  cmd="yadm"
fi

echo_run "$cmd" fetch "$@"

# if needs_git_cleanup; then
#   git_cleanup
# fi
