#!/usr/bin/env zsh

local cmd="git"
if ! in-git-repo; then
  echo-info "Not in git repository. Using yadm."
  cmd="yadm"
fi

echo-run "$cmd" fetch "$@"

# if needs_git_cleanup; then
#   git_cleanup
# fi
