#!/usr/bin/env zsh

local line
[ -e tags ] &&
line=$(
  rg "$1" tags |
  awk 'BEGIN { FS="\t" } !/^!/ {print toupper($4)"\t"$1"\t"$2"\t"$3}' |
  fzf \
    --nth=1,2 \
    --with-nth=2,3 \
    --preview-window="up:50%" \
    --preview="head -n 10000 {3}" \
    --tabstop=2 \
    --delimiter="\t" \
    --query="$1"
) && ${EDITOR:-vim} $(cut -f3 <<< "$line") -c "set nocst" \
                                    -c "silent tag $(cut -f2 <<< "$line")"
