#! /usr/bin/env zsh

if [ ${#@} -gt 0 ]; then
  git "$@"
else
  [ -d .git ] || git rev-parse --git-dir > /dev/null 2>&1
  if (( $status )); then
    printf "Not in a git repository.\n"
    return 128
  fi
  echo_run git status && \
  echo_run git stash list
fi
