#!/usr/bin/env zsh

local remote_branches=($(
  git for-each-ref --sort=committerdate refs/remotes/origin \
    --format='%(authoremail) %(refname)' \
    | grep -E '(george\.witteman@affirm\.com|george@witteman\.me)' \
    | grep origin \
    | cut -d ' ' -f 2))

local branches=(${(M)remote_branches/#refs\/remotes\/origin\//})

echo "${(j:\n:)branches}"
