#!/usr/bin/env zsh

if ! in-git-repo; then
  echo "Not in git repository."
  return 128
fi

local git_dir="$(git rev-parse --git-dir)"

if [[ -f "$git_dir/gc.log" ]]; then
  echo-eval "cat $git_dir/gc.log && rm $git_dir/gc.log"
  echo-run git prune
fi

echo-run git remote prune origin
echo-run git gc
