#!/usr/bin/env zsh

if ! in_git_repo; then
  echo "Not in git repository."
  return 128
fi

local git_dir="$(git rev-parse --git-dir)"

if [[ -f "$git_dir/gc.log" ]]; then
  echo_run cat "$git_dir/gc.log"
  echo_run rm "$git_dir/gc.log"
fi

echo_run git remote prune origin
echo_run git gc
