#!/usr/bin/env zsh

local exports_dir="$HOME/.gnupg/.exports"
mkdir -p "$exports_dir"
echo "Exporting to $exports_dir"
echo_run gpg --armor --export > "$exports_dir/pgp-public-keys.asc"
echo_run gpg --armor --export-secret-keys > "$exports_dir/pgp-private-keys.asc"
echo_run gpg --export-ownertrust > "$exports_dir/pgp-ownertrust.asc"
echo_run ls -l "$exports_dir"
echo_run yadm encrypt
echo_run yadm status
