#!/usr/bin/env zsh

if ! in_git_repo; then
  echo_err "Not in git repository."
  return 128
fi

echo_info -n "Getting remote HEAD... "
GIT_HEAD="$(get_remote_head)"
echo $GIT_HEAD

echo_run git checkout --quiet $GIT_HEAD && \
echo_run git fetch --quiet --progress --force --prune --tags && \
echo_run git merge --quiet --ff-only origin/$GIT_HEAD && \
echo_run git show --quiet --pretty=short HEAD # --quiet supresses the diff

# if needs_git_cleanup; then
#   git_cleanup
# fi
