#!/usr/bin/env zsh

if ! in_git_repo; then
  return 128
fi

local git_dir="$(git rev-parse --git-dir)"
if [[ -f "$git_dir/gc.log" ]]; then
  echo
  echo "${fg_bold[yellow]}The REPO/.git/gc.log file exists. Need to run git_cleanup!$reset_color"
  return 0
fi

return 1
