#!/usr/bin/env zsh

local start_time shell now startup_diff max_time time_color
zmodload zsh/datetime
shell=$SHELL

# login interactive
start_time=$EPOCHREALTIME

ZPROF=true $shell "$@" -c 'zprof; exit'

time_color="${fg_bold[default]}"
startup_diff=$((($EPOCHREALTIME * 1000) - ($start_time * 1000)))

(( $startup_diff >= 100 )) && \
  time_color="${fg_bold[red]}"

echo "'zsh $@' startup took ${time_color}${startup_diff[0,8]}ms${reset_color}"
