#!/usr/bin/env zsh

local line
local pyobj

if [ -p /dev/stdin ]; then
  while read line; do
    pyobj+="$line\n"
  done
  pyobj+="$line"
else
  pyobj="$@"
fi

local from_clipboard
if [[ -z "$pyobj" ]]; then
  pyobj="$(pbpaste)"
  from_clipboard=1
fi

if [[ -z "$pyobj" ]]; then
  return
fi

# The `-` means read from stdin
local output="$(python3 - << EOF
import json
try:
    obj = $pyobj
    print(json.dumps(obj, indent=2))
except Exception as e:
    print('Error parsing python object')
    print(e)
EOF
)"

if [[ -n "$from_clipboard" ]]; then
  echo "$output" | pbcopy
fi

echo "$output"
