#!/usr/bin/env zsh

if [[ "$1" != "" ]]; then
  echo_run git fetch --quiet --tags --prune && \
  echo_run git rebase $@
  return $?
fi

get_remote_head

echo_run git fetch --quiet --prune --tags && \
echo_run git rebase origin/$GIT_HEAD "$@"
