#!/usr/bin/env zsh

if ! in_git_repo; then
  echo_err "Not in git repository."
  return 128
fi

if [[ "$1" == "" ]]; then
  echo_info -n "Getting remote HEAD... "
  GIT_HEAD="$(get_remote_head)"
  echo $GIT_HEAD

  echo_run git fetch --prune --quiet --tags && \
  echo_run git rebase origin/$GIT_HEAD
  return $?
fi

if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
  echo "Usage: $0 [<git rebase args>]"
  return
fi

echo_run git fetch --prune --quiet --tags && \
echo_run git rebase $@

# if needs_git_cleanup; then
#   git_cleanup
# fi
