#!/usr/bin/env zsh
local N=${1:-50}
local args=("$HOME/.zshrc")
start_timer "vim ${args[@]} +qall"
repeat $N { vim "${args[@]}" +qall }
end_timer $N

start_timer "vim --clean ${args[@]} +qall"
repeat $N { vim --clean "${args[@]}" +qall }
end_timer $N

start_timer "vim -u NONE ${args[@]} +qall"
repeat $N { vim -u NONE "${args[@]}" +qall }
end_timer $N
