#!/usr/bin/env zsh

_helper() {
  local start_time shell now startup_diff max_time time_color
  zmodload zsh/datetime
  shell=$SHELL

  # login interactive
  start_time=$EPOCHREALTIME

  $shell "$@" -c 'exit'

  time_color="${bold_color}"
  startup_diff=$((($EPOCHREALTIME * 1000) - ($start_time * 1000)))

  (( $startup_diff >= 100 )) && \
    time_color="${fg_bold[red]}"

  echo "${bold_color}'zsh $@'${reset_color} startup took ${time_color}${startup_diff[0,8]}ms${reset_color}"
}

if (( $+commands[hyperfine] )); then
  shell_command="$SHELL $@ -c exit"
  hyperfine $shell_command
else
  for i in $(seq 1 10); do _helper "$@"; done
fi
