 {{- $refreshPeriodDay := "24h" -}}
 {{- $refreshPeriodWeek := "168h" -}}

# Removing this for now since it's being annoying
# .cache/fast-syntax-highlighting:
#   type: archive
#   url: 'https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz'
#   exact: true
#   stripComponents: 1
#   refreshPeriod: {{ $refreshPeriodWeek }}

{{ if eq .chezmoi.os "darwin" }}
.cache/iterm2/iterm2_shell_integration.bash:
  type: file
  url: 'https://gitlab.com/gnachman/iterm2/-/raw/master/Resources/shell_integration/iterm2_shell_integration.bash'
  refreshPeriod: {{ $refreshPeriodWeek }}

.cache/iterm2/iterm2_shell_integration.zsh:
  type: file
  url: 'https://gitlab.com/gnachman/iterm2/-/raw/master/Resources/shell_integration/iterm2_shell_integration.zsh'
  refreshPeriod: {{ $refreshPeriodWeek }}
{{ end }}

.local/share/zsh/zsh-completions:
  type: git-repo
  url: 'https://github.com/zsh-users/zsh-completions.git'
  refreshPeriod: {{ $refreshPeriodDay }}

.local/share/zsh/functions/_alacritty:
  type: file
  url: 'https://raw.githubusercontent.com/alacritty/alacritty/master/extra/completions/_alacritty'
  refreshPeriod: {{ $refreshPeriodWeek }}

.local/share/zsh/functions/_cargo:
  type: file
  url: 'https://raw.githubusercontent.com/rust-lang/cargo/master/src/etc/_cargo'
  refreshPeriod: {{ $refreshPeriodWeek }}

.local/share/zsh/functions/_fd:
  type: file
  url: 'https://raw.githubusercontent.com/sharkdp/fd/master/contrib/completion/_fd'
  refreshPeriod: {{ $refreshPeriodWeek }}

.local/share/zsh/functions/_node:
  type: file
  url: 'https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_node'
  refreshPeriod: {{ $refreshPeriodWeek }}

.local/share/zsh/functions/_rg:
  type: file
  url: 'https://raw.githubusercontent.com/BurntSushi/ripgrep/master/complete/_rg'
  refreshPeriod: {{ $refreshPeriodWeek }}

.local/share/zsh/functions/_docker:
  type: file
  url: 'https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker'
  refreshPeriod: {{ $refreshPeriodWeek }}

.local/share/zsh/functions/_docker-compose:
  type: file
  url: 'https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose'
  refreshPeriod: {{ $refreshPeriodWeek }}

.pyenv:
  type: git-repo
  url: 'https://github.com/pyenv/pyenv.git'
  refreshPeriod: {{ $refreshPeriodWeek }}
  pull:
    args: ["--rebase", "--autostash"]

.nvm:
  type: git-repo
  url: 'https://github.com/nvm-sh/nvm.git'
  refreshPeriod: {{ $refreshPeriodWeek }}
  pull:
    # Only do the initial clone
    args: ["--dry-run"]
    # args: ["--rebase", "--autostash"]

# VIM PLUGINS ================================
{{ define "vim-plugin" }}
  type: git-repo
  url: {{ . | quote }}
  refreshPeriod: "168h"
{{ end -}}

{{ define "github-vim-plugin" }}
.vim/pack/plugins/start/{{ base . }}:
  {{- template "vim-plugin" (list "https://github.com/" . ".git" | join "") }}{{ end -}}

# Enables useful syntax highlighting for .tmpl and other chezmoi files
.vim/pack/plugins/opt/chezmoi.vim:
{{- template "vim-plugin" "https://github.com/alker0/chezmoi.vim.git" }}

# Nord color scheme
.vim/pack/plugins/opt/nord-vim:
  {{- template "vim-plugin" "https://github.com/arcticicestudio/nord-vim.git" }}

# Filetypes

# "Yaml files in vim 7.4 are really slow, due to core yaml syntax. This syntax
# is simpler/faster." - stephpy/vim-yaml/README.md
{{- template "github-vim-plugin" "stephpy/vim-yaml" }}

# Adds better python syntax highlighting (e.g. indent errors, exception
# classes, builtins, etc.)
{{- template "github-vim-plugin" "hdima/python-syntax" }}

# Use proper indentation formatting for python
{{- template "github-vim-plugin" "Vimjas/vim-python-pep8-indent" }}

# Adds support for justfile syntax
{{- template "github-vim-plugin" "NoahTheDuke/vim-just" }}

# Commenting these out so that when I add them back I can write down what they
# do and why I have them
# { {- template "github-vim-plugin" (list "gisphm/vim-gitignore" "master") }}
# { {- template "github-vim-plugin" (list "chrisbra/vim-zsh" "master") }}
# { {- template "github-vim-plugin" (list "elzr/vim-json" "master") }}
# { {- template "github-vim-plugin" (list "lifepillar/pgsql.vim" "master") }}
# { {- template "github-vim-plugin" (list "saltstack/salt-vim" "master") }}
# { {- template "github-vim-plugin" (list "pboettch/vim-cmake-syntax" "master") }}
# { {- template "github-vim-plugin" (list "plasticboy/vim-markdown" "master") }}
# { {- template "github-vim-plugin" (list "raimon49/requirements.txt.vim" "master") }}
# { {- template "github-vim-plugin" (list "chrismaher/vim-dbt" "master") }}
# { {- template "github-vim-plugin" (list "jalvesaq/Nvim-R" "master") }}
# { {- template "github-vim-plugin" (list "chrisbra/csv.vim" "master") }}
# { {- template "github-vim-plugin" (list "hashivim/vim-terraform" "master") }}
# { {- template "github-vim-plugin" (list "darfink/vim-plist" "master") }}
# { {- template "github-vim-plugin" (list "rust-lang/rust.vim" "master") }}
# { {- template "github-vim-plugin" (list "Glench/Vim-Jinja2-Syntax" "master") }}

# Allows calling arbitrary git commands and other things
.vim/pack/plugins/opt/vim-fugitive:
{{- template "vim-plugin" "https://github.com/tpope/vim-fugitive.git" }}

# GitHub plugin for vim-fugitive
.vim/pack/plugins/opt/vim-rhubarb:
{{- template "vim-plugin" "https://github.com/tpope/vim-rhubarb.git" }}

# FZF support
.vim/pack/plugins/opt/fzf:
{{- template "vim-plugin" "https://github.com/junegunn/fzf.git" }}

.vim/pack/plugins/opt/fzf.vim:
{{- template "vim-plugin" "https://github.com/junegunn/fzf.vim.git" }}

# For automatically creating tags files
.vim/pack/plugins/opt/vim-gutentags:
{{- template "vim-plugin" "https://github.com/ludovicchabant/vim-gutentags.git" }}

# Better text
{{- template "github-vim-plugin" "reedes/vim-pencil" }}

# Improved incremental search
{{- template "github-vim-plugin" "haya14busa/is.vim" }}

# A better (and faster) file manager than netrw
{{- template "github-vim-plugin" "justinmk/vim-dirvish" }}

# Strips whitespace when closing files
{{- template "github-vim-plugin" "ntpeters/vim-better-whitespace" }}

# Adds capslock shortcut
{{- template "github-vim-plugin" "tpope/vim-capslock" }}

# Shortcuts for commenting out lines/blocks of lines
{{- template "github-vim-plugin" "tpope/vim-commentary" }}

# Adds `:Make` for asynchronous makes
{{- template "github-vim-plugin" "tpope/vim-dispatch" }}

# Allows repeating non-default shortcuts
{{- template "github-vim-plugin" "tpope/vim-repeat" }}

# Adds shortcuts for surrounding items with things
{{- template "github-vim-plugin" "tpope/vim-surround" }}

# Support for the Prisma ORM
{{- template "github-vim-plugin" "pantharshit00/vim-prisma" }}

# Support for clipboard over SSH via ANSI OSC52 sequence
{{- template "github-vim-plugin" "ojroques/vim-oscyank" }}
