 {{- $refreshPeriod := "168h" -}}

.cache/fast-syntax-highlighting:
  type: archive
  url: 'https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: {{ $refreshPeriod }}

.cache/iterm2/iterm2_shell_integration.bash:
  type: file
  url: 'https://gitlab.com/gnachman/iterm2/-/raw/master/Resources/shell_integration/iterm2_shell_integration.bash'
  refreshPeriod: {{ $refreshPeriod }}

.cache/iterm2/iterm2_shell_integration.zsh:
  type: file
  url: 'https://gitlab.com/gnachman/iterm2/-/raw/master/Resources/shell_integration/iterm2_shell_integration.zsh'
  refreshPeriod: {{ $refreshPeriod }}

.config/zsh/_alacritty:
  type: file
  url: 'https://raw.githubusercontent.com/alacritty/alacritty/master/extra/completions/_alacritty'
  refreshPeriod: {{ $refreshPeriod }}

.config/zsh/_cargo:
  type: file
  url: 'https://raw.githubusercontent.com/rust-lang/cargo/master/src/etc/_cargo'
  refreshPeriod: {{ $refreshPeriod }}

.config/zsh/_fd:
  type: file
  url: 'https://raw.githubusercontent.com/sharkdp/fd/master/contrib/completion/_fd'
  refreshPeriod: {{ $refreshPeriod }}

.config/zsh/_node:
  type: file
  url: 'https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_node'
  refreshPeriod: {{ $refreshPeriod }}

.config/zsh/_rg:
  type: file
  url: 'https://raw.githubusercontent.com/BurntSushi/ripgrep/master/complete/_rg'
  refreshPeriod: {{ $refreshPeriod }}

.pyenv:
  type: archive
  url: 'https://github.com/pyenv/pyenv/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: {{ $refreshPeriod }}

.nvm:
  type: archive
  url: 'https://github.com/nvm-sh/nvm/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: {{ $refreshPeriod }}

# VIM PLUGINS ================================
{{ define "vim-plugin" }}
  type: archive
  url: {{ . | quote }}
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
{{ end -}}

{{ define "github-vim-plugin" }}
.vim/pack/plugins/start/{{ base (index . 0) }}:
  {{- template "vim-plugin" (list "https://github.com/" (index . 0) "/archive/" (index . 1) ".tar.gz" | join "") }}{{ end -}}

# Enables useful syntax highlighting for .tmpl and other chezmoi files
.vim/pack/plugins/opt/chezmoi.vim:
{{- template "vim-plugin" "https://github.com/alker0/chezmoi.vim/archive/main.tar.gz" }}

# Nord color scheme
.vim/pack/plugins/opt/nord-vim:
  {{- template "vim-plugin" "https://github.com/arcticicestudio/nord-vim/archive/develop.tar.gz" }}

# Commenting these out so that when I add them back I can write down what they
# do and why I have them
# { {- template "github-vim-plugin" (list "cespare/vim-toml" "main") }}
# { {- template "github-vim-plugin" (list "gisphm/vim-gitignore" "master") }}
# { {- template "github-vim-plugin" (list "chrisbra/vim-zsh" "master") }}
# { {- template "github-vim-plugin" (list "elzr/vim-json" "master") }}
# { {- template "github-vim-plugin" (list "lifepillar/pgsql.vim" "master") }}
# { {- template "github-vim-plugin" (list "saltstack/salt-vim" "master") }}
# { {- template "github-vim-plugin" (list "pboettch/vim-cmake-syntax" "master") }}
# { {- template "github-vim-plugin" (list "plasticboy/vim-markdown" "master") }}
# { {- template "github-vim-plugin" (list "stephpy/vim-yaml" "master") }}
# { {- template "github-vim-plugin" (list "Vimjas/vim-python-pep8-indent" "master") }}
# { {- template "github-vim-plugin" (list "raimon49/requirements.txt.vim" "master") }}
# { {- template "github-vim-plugin" (list "hdima/python-syntax" "master") }}
# { {- template "github-vim-plugin" (list "chrismaher/vim-dbt" "master") }}
# { {- template "github-vim-plugin" (list "jalvesaq/Nvim-R" "master") }}
# { {- template "github-vim-plugin" (list "chrisbra/csv.vim" "master") }}
# { {- template "github-vim-plugin" (list "hashivim/vim-terraform" "master") }}
# { {- template "github-vim-plugin" (list "darfink/vim-plist" "master") }}
# { {- template "github-vim-plugin" (list "rust-lang/rust.vim" "master") }}
# { {- template "github-vim-plugin" (list "Glench/Vim-Jinja2-Syntax" "master") }}

{{- if lookPath "git" }}
# Allows calling arbitrary git commands and other things
{{- template "github-vim-plugin" (list "tpope/vim-fugitive" "master") }}

# GitHub plugin for vim-fugitive
{{- template "github-vim-plugin" (list "tpope/vim-rhubarb" "master") }}
{{ end }}

{{- if lookPath "fzf" }}
# FZF support
{{- template "github-vim-plugin" (list "junegunn/fzf" "master") }}
{{- template "github-vim-plugin" (list "junegunn/fzf.vim" "master") }}
{{ end }}

# Better text
{{- template "github-vim-plugin" (list "reedes/vim-pencil" "master") }}

# Improved incremental search
{{- template "github-vim-plugin" (list "haya14busa/is.vim" "master") }}

# A better (and faster) file manager than netrw
{{- template "github-vim-plugin" (list "justinmk/vim-dirvish" "master") }}

# For automatically creating tags files
{{- template "github-vim-plugin" (list "ludovicchabant/vim-gutentags" "master") }}

# Strips whitespace when closing files
{{- template "github-vim-plugin" (list "ntpeters/vim-better-whitespace" "master") }}

# Adds capslock shortcut
{{- template "github-vim-plugin" (list "tpope/vim-capslock" "master") }}

# Shortcuts for commenting out lines/blocks of lines
{{- template "github-vim-plugin" (list "tpope/vim-commentary" "master") }}

# Adds `:Make` for asynchronous makes
{{- template "github-vim-plugin" (list "tpope/vim-dispatch" "master") }}

# Allows repeating non-default shortcuts
{{- template "github-vim-plugin" (list "tpope/vim-repeat" "master") }}

# Adds shortcuts for surrounding items with things
{{- template "github-vim-plugin" (list "tpope/vim-surround" "master") }}
