[".vim/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "168h"

[".cache/fast-syntax-highlighting"]
type = "archive"
url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".config/zsh/_alacritty"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty/master/extra/completions/_alacritty"
refreshPeriod = "168h"

[".config/zsh/_cargo"]
type = "file"
url = "https://raw.githubusercontent.com/rust-lang/cargo/master/src/etc/_cargo"
refreshPeriod = "168h"
