image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker

tasks:
  - name: Install dotfiles
    # This needs to be command because init will only save changes to /workspace
    # when run as a prebuild.
    command: |
      sh -xe install.sh
