vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker

tasks:
  - name: Install dotfiles
    before: sudo apt-get update && sudo apt-get install --yes neovim shellcheck
    command: sh -xe install.sh && exit 0
