vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker

tasks:
  - name: Install dotfiles
    # This needs to be command because init will only save changes to /workspace
    # when run as a prebuild.
    command: |
      set -o errexit
      set -o xtrace
      sudo apt-get update
      sudo apt-get install --yes neovim
      sh -xe install.sh
