#!/usr/bin/env bash

source "${HOME}/.shinit"

if [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]]; then
  . "/usr/local/etc/profile.d/bash_completion.sh"
fi

for dir in "$HOME"/.config/sh/*/; do
  [ -d "$dir" ] || continue

  # shellcheck disable=SC1090
  [ -r "${dir}init.bash" ] && . "${dir}init.bash"
done
