#!/usr/bin/env bash

if [[ -z $ENV ]]; then
  # If ~/.bash_profile wasn't sourced then source it
  # shellcheck source=.bash_profile
  source "${HOME}/.bash_profile"
  return $?
fi

# shellcheck source=.shinit
source "${HOME}/.shinit"

for dir in "$HOME"/.config/sh/*; do
  if [[ ! -d $dir ]]; then
    continue
  fi

  if [[ -r ${dir}/init.bash ]]; then
    # shellcheck source=/dev/null
    source "${dir}/init.bash"
  fi
done

# Keep this at the end
if [[ -e "${HOME}/.cache/iterm2/iterm2_shell_integration.bash" ]]; then
  # shellcheck source=/dev/null
  source "${HOME}/.cache/iterm2/iterm2_shell_integration.bash" || true
fi
