#!/bin/sh

export ENV="${HOME}/.shinit"

# Skipping this for now because there is some improvement when running python
# tests
# # Don't write python .pyc files, because they're not necessary and clutter
# # directories with binary files
# export PYTHONDONTWRITEBYTECODE=1

# Locale setup
export LC_ALL="${LC_ALL:-en_US.UTF-8}"
export LANG="${LANG:-en_US.UTF-8}"

if command -v nvim >/dev/null 2>&1; then
  export EDITOR="${EDITOR:-nvim}"
else
  export EDITOR="${EDITOR:-vim}"
fi

export PAGER="${PAGER:-less -R}"
export MANPAGER="${MANPAGER:-less -is}"
export CLICOLOR="${CLICOLOR:-1}"
export LSCOLORS="${LSCOLORS:-exfxcxdxbxegedabagacad}"
export LS_COLORS="${LS_COLORS:-di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43}"

export LESSHISTFILE="${LESSHISTFILE:-/dev/null}"

export FZF_DEFAULT_COMMAND="${FZF_DEFAULT_COMMAND:-fd --type f --hidden --exclude .git}"

# Fixes gpg when "GPG Suite" is not installed (i.e. gpg is installed from homebrew)
export GPG_TTY="$TTY"

# https://github.com/Homebrew/brew/pull/10374
export HOMEBREW_NO_ANALYTICS=1
# Turning these off because I'm constantly getting issues with homebrew
# and maybe these are causing it
# export HOMEBREW_BOOTSNAP=1
# export HOMEBREW_INSTALL_FROM_API=1

# https://stackoverflow.com/a/9168577
export PRIVATE_BIN="${HOME}/.bin"

if [ -S "${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock" ]; then
  export SSH_AUTH_SOCK="${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
fi

PATH="/usr/local/sbin:${PATH}"
PATH="/usr/local/opt/fzf/bin:${PATH}"
PATH="${HOME}/.local/bin:${PATH}"
PATH="$PRIVATE_BIN:${PATH}"
PATH="${HOME}/.cargo/bin:${PATH}"

for dir in "$HOME"/.config/sh/*/; do
  [ -d "$dir" ] || continue
  if [ -d "${dir}/bin" ]; then
    PATH="${dir}bin:${PATH}"
  fi

  # shellcheck disable=SC1090
  if [ -r "${dir}profile.sh" ]; then
    . "${dir}profile.sh"
  fi
done
