#!/usr/bin/env zsh

if [[ "$OSTYPE" = "darwin"* ]]; then
  # This causes zsh not to run /etc/{zshenv,zprofile,zshrc}
  unsetopt GLOBAL_RCS

  typeset -U path
  typeset -gx PATH
  # typeset file

  # Setup default PATH just like /etc/zprofile does
  # path=("${(f)$(</etc/paths)}" ${path[@]})
  # for file in /etc/paths.d/*(N); do
  #   path=("${(f)$(<${file})}" ${path[@]})
  # done
  # unset file
  # if [[ -x "/usr/libexec/path_helper" ]]; then
  #   eval $(/usr/libexec/path_helper -s)
  # fi
  path=("/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" ${path[@]})
fi

# Locale setup
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# Correctly display UTF-8 with combining characters.
setopt COMBINING_CHARS

# Disable the log builtin, so we don't conflict with /usr/bin/log
disable log

if [[  -d "$HOME/.local/bin" ]]; then
  path=("$HOME/.local/bin" "${path[@]}")
fi

# if (( ! $+commands[fzf] )) && [[ -d "/usr/local/opt/fzf/bin" ]]; then
if ! whence fzf >/dev/null && [[ -d "/usr/local/opt/fzf/bin" ]]; then
  path=("/usr/local/opt/fzf/bin" "${path[@]}")
fi

# Add arcanist to path if it's installed
if [[ -d "$HOME/.phabricator/arcanist/bin" ]]; then
  path=("$HOME/.phabricator/arcanist/bin" "${path[@]}")
fi

# Rust
if [[ -d "$HOME/.cargo/bin" ]]; then
  path=("$HOME/.cargo/bin" "${path[@]}")
fi
