#!/bin/sh

# `man dash`: If the environment variable ENV is set on entry to an interactive
# shell, or is set in the .profile of a login shell, the shell next reads
# commands from the file named in ENV.  Therefore, a user should place commands
# that are to be executed only at login time in the .profile file, and commands
# that are executed for every interactive shell inside the ENV file.
export ENV="${HOME}/.shinit"

# This variable configures all programs which use setlocale(3) to use the specified locale unless the LC_* variables are set.
export LANG="${LANG:-en_US.UTF-8}"

# `man environ`: Default editor name.
if [ -z "$EDITOR" ]; then
  if command -v nvim >/dev/null 2>&1; then
    export EDITOR="nvim"
  else
    export EDITOR="vim"
  fi
fi

# Fixes gpg when "GPG Suite" is not installed (i.e. gpg is installed from homebrew)
if [ -n "$TTY" ]; then
  export GPG_TTY="$TTY"
fi

export PRIVATE_BIN="${HOME}/.bin"

if [ -S "${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock" ]; then
  # `man ssh`: SSH_AUTH_SOCK Identifies the path of a UNIX-domain socket used
  # to communicate with the agent.
  export SSH_AUTH_SOCK="${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
fi

if [ -z "$PATH" ]; then
  export PATH="/sbin:/bin:/usr/sbin:/usr/bin"
fi

# Always add things to PATH so that I can use them directly after installing
# without needing to restart my terminal.
PATH="/usr/local/sbin:${PATH}"
PATH="/usr/local/opt/fzf/bin:${PATH}"
PATH="${HOME}/.local/bin:${PATH}"
PATH="${PRIVATE_BIN}:${PATH}"
PATH="${HOME}/.cargo/bin:${PATH}"
PATH="${HOME}/.poetry/bin:${PATH}"

for dir in "$HOME"/.config/sh/*; do
  if [ ! -d "$dir" ]; then
    continue
  fi

  if [ -d "${dir}/bin" ]; then
    PATH="${dir}/bin:${PATH}"
  fi

  if [ -r "${dir}/profile.sh" ]; then
    # shellcheck source=/dev/null
    . "${dir}/profile.sh"
  fi
done
