[".local/share/zsh/zsh-completions"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-completions.git"
  refreshPeriod = "24h"

[".local/share/zsh/functions/_cargo"]
  type = "file"
  url = "https://raw.githubusercontent.com/rust-lang/cargo/master/src/etc/_cargo"
  refreshPeriod = "24h"

[".local/share/zsh/functions/_fd"]
  type = "file"
  url = "https://raw.githubusercontent.com/sharkdp/fd/master/contrib/completion/_fd"
  refreshPeriod = "24h"

[".local/share/zsh/functions/_node"]
  type = "file"
  url = "https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_node"
  refreshPeriod = "24h"

[".local/share/zsh/functions/_rg"]
  type = "file"
  url = "https://raw.githubusercontent.com/BurntSushi/ripgrep/master/crates/core/flags/complete/rg.zsh"
  refreshPeriod = "24h"

[".local/share/zsh/functions/_docker"]
  type = "file"
  url = "https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker"
  refreshPeriod = "24h"

[".local/share/zsh/functions/_docker-compose"]
  type = "file"
  url = "https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose"
  refreshPeriod = "24h"

[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "24h"

{{- if (or (eq (env "NVM_DIR") (joinPath .chezmoi.homeDir ".nvm")) (empty (env "NVM_DIR"))) }}

[".nvm"]
  type = "git-repo"
  url = "https://github.com/nvm-sh/nvm.git"
  refreshPeriod = "24h"

  # Only do the initial clone
  pull = { args = ["--dry-run"] }
  # pull = { args = ["--rebase", "--autostash"] }
{{- end }}
