#!/bin/sh
# `man dash`: If the environment variable ENV is set on entry to an interactive
# shell, or is set in the .profile of a login shell, the shell next reads
# commands from the file named in ENV.  Therefore, a user should place commands
# that are to be executed only at login time in the .profile file, and commands
# that are executed for every interactive shell inside the ENV file.
#
# WARNING: If for whatever reason this gets removed make sure to update the
# check at the top of ~/.bashrc.
export ENV="${HOME}/.shinit"

# This variable configures all programs which use setlocale(3) to use the specified locale unless the LC_* variables are set.
export LANG="${LANG:-en_US.UTF-8}"

# `man environ`: Default editor name.
if [ -z "$EDITOR" ]; then
  if [ -n "$REMOTE_CONTAINERS" ] && command -v code >/dev/null 2>&1; then
    export EDITOR="code"
  else
    export EDITOR="vim"
  fi
fi

if [ -S "${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock" ]; then
  # `man ssh`: SSH_AUTH_SOCK Identifies the path of a UNIX-domain socket used
  # to communicate with the agent.
  export SSH_AUTH_SOCK="${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
fi

if [ -z "$PATH" ]; then
  export PATH="/sbin:/bin:/usr/sbin:/usr/bin"
fi

# Check if we're in zsh (.zprofile is symlinked to .profile) and that we're
# running in the Apple Terminal. We check for Apple Terminal since the file
# that contains the code we're trying to disable is in the
# /etc/zshrc_Apple_Terminal file and that file is only loaded if we're in the
# Apple Terminal.
if [ -n "$ZSH_VERSION" ] && [ "$TERM_PROGRAM" = "Apple_Terminal" ]; then
  # Disable shell save/restore mechanism. See /etc/zshrc_Apple_Terminal
  # shellcheck disable=SC2034
  SHELL_SESSIONS_DISABLE=1
fi

# From installer: ==> Next steps:
# - Run these two commands in your terminal to add Homebrew to your PATH:
#     echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/<user>/.zprofile
#     eval "$(/opt/homebrew/bin/brew shellenv)"
if [ -x "/opt/homebrew/bin/brew" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv || true)"
fi

# Always add things to PATH so that I can use them directly after installing
# without needing to restart my terminal.
PATH="/usr/local/sbin:${PATH}"
PATH="/usr/local/opt/fzf/bin:${PATH}"
PATH="${HOME}/.local/bin:${PATH}"
PATH="${HOME}/.scripts:${PATH}"
PATH="${HOME}/.cargo/bin:${PATH}"
PATH="${HOME}/.poetry/bin:${PATH}"
PATH="${HOME}/.bun/bin:${PATH}"

if [ -z "$NVM_DIR" ]; then
  export NVM_DIR="${HOME}/.nvm"
fi

# Added to prevent nvm install script from adding it
if false; then
  # shellcheck disable=SC1091
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi
