#!/usr/bin/env bash

if [[ -z $ENV ]]; then
  # If ~/.bash_profile wasn't sourced then source it
  # shellcheck source=.bash_profile
  source "${HOME}/.bash_profile"
  return $?
fi

# shellcheck source=.shinit
source "${HOME}/.shinit"

if command -v "gh" &>/dev/null; then
  eval "$(gh completion --shell bash || true)"
fi

# https://docs.brew.sh/Shell-Completion
if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
  # shellcheck source=/dev/null
  source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
elif [[ -d "${HOMEBREW_PREFIX}/etc/bash_completion.d" ]]; then
  for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
    if [[ -r ${COMPLETION} ]]; then
      # shellcheck source=/dev/null
      source "${COMPLETION}"
    fi
  done
  unset COMPLETION
fi

# https://github.com/nvm-sh/nvm#manual-install
# shellcheck disable=SC1091,SC2292
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# shellcheck disable=SC1091,SC2292
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# https://github.com/posener/complete/blob/v1/cmd/install/bash.go
# https://github.com/posener/complete/blob/9a4745ac49b29530e07dc2581745a218b646b7a3/cmd/install/install.go#L86-L89
if command -v "terraform" &>/dev/null; then
  # shellcheck disable=SC2312
  complete -C "$(command -v terraform)" terraform
fi

if command -v starship >/dev/null 2>/dev/null; then
  # shellcheck disable=SC2312
  eval "$(starship init bash)"
else
  PS1='\[\033[01;34m\]\w\[\033[00m\] \$ '
fi

# Generated for envman. Do not edit.
# shellcheck disable=SC2292
# shellcheck source=/dev/null
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"
