#!/usr/bin/env zsh

# Stop when any command fails
set -e

set_local_bin_path() {
  export PATH="$HOME/.local/bin:$PATH"
}

bootstrap_platform() {
  if [[ "$OSTYPE" =~ "darwin" ]]; then
    echo_run bootstrap_macos
  else
    echo "No platform bootstrap script for $OSTYPE"
  fi
}

install_submodules() {
  echo "Init submodules"
  echo_run yadm submodule update --recursive --init
}

install_homebrew_zsh() {
  local zsh_path="$(brew --prefix)/bin/zsh"
  # -q be quiet
  # -x match the whole line
  # -F pattern is a plain string
  if grep -qxF "$zsh_path" /etc/shells; then
    echo "$zsh_path already in /etc/shells"
    if [[ "$SHELL" != "$zsh_path" ]]; then
      echo "Setting shell to $zsh_path"
      echo_run chsh -s "$zsh_path"
    fi
  else
    echo "Adding $zsh_path to /etc/shells"
    echo "$zsh_path" | sudo tee -a /etc/shells >/dev/null
    echo "Setting shell to $zsh_path"
    echo_run chsh -s "$zsh_path"
  fi
}

bootstrap_asdf() {
  if ! command -v asdf >/dev/null 2>&1; then
    echo "Installing asdf"
    echo_run git clone https://github.com/asdf-vm/asdf.git ~/.asdf
    cd ~/.asdf
    echo_run git checkout "$(git describe --abbrev=0 --tags)"
  fi
}

install_alacritty_terminfo() {
  echo "Compiling alacritty terminfo file"
  TMP_DIR=$(mktemp -d)
  cd $TMP_DIR
  echo_run curl -O https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info
  echo_run tic -xe alacritty,alacritty-direct alacritty.info
  cd
  rm -rf $TMP_DIR
}

bootstrap_tmux() {
  echo "Installing tmux terminfo file"
  echo_run tic -x $XDG_CONFIG_HOME/tmux/tmux.terminfo

  if command -v tmux >/dev/null 2>&1; then
    echo "Installing, updating, and cleaning tmux plugins"

    if [ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tpm" ]; then
      echo_run git clone https://github.com/tmux-plugins/tpm \
        "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tpm"
    fi

    echo_run ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tpm/bin/install_plugins
    echo_run ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tpm/bin/update_plugins all
    echo_run ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tpm/bin/clean_plugins
  fi
}

decrypt_yadm_files() {
  echo_run yadm decrypt
  echo_run chmod 700 ~/.ssh
  echo_run chmod 600 ~/.ssh/id_rsa
  echo_run chmod 644 ~/.ssh/id_rsa.pub
  echo_run gpg --import ~/.gnupg/.exports/pgp-public-keys.asc
  echo_run gpg --import ~/.gnupg/.exports/pgp-private-keys.asc
  echo_run gpg --import-ownertrust ~/.gnupg/.exports/pgp-ownertrust.asc
}

update_yadm_url_to_ssh() {
  # We now have ssh keys decrypted, so can update the url
  # to be the ssh url
  echo "Updating the yadm repo origin URL"
  echo_run yadm remote set-url origin "git@github.com:georgewitteman/dotfiles.git"
}

reminders() {
  echo
  echo "REMINDERS:"
  echo " - Don't forget to download the SF Mono font from https://developer.apple.com/fonts/"
  echo " - Don't forget to set yadm class!"
  echo "     $ yadm config local.class <work|personal>"
}

set_local_bin_path
bootstrap_platform
decrypt_yadm_files
update_yadm_url_to_ssh
install_submodules
install_homebrew_zsh
bootstrap_asdf
install_alacritty_terminfo
bootstrap_tmux

reminders
