#!/bin/sh

set -o errexit

push=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h | --help)
      echo "usage: $(basename "$0") [-p|--push]"
      exit
      ;;
    -p | --push)
      push=true
      ;;
    -*)
      echo-err "unknown option: ${1}"
      exit 1
      ;;
    *)
      break
      ;;
  esac
  shift
done

printf "Getting remote HEAD... "
GIT_HEAD="$(get-main-branch)"
echo "$GIT_HEAD"

previous_head="$(git rev-parse --short HEAD)"

if git ls-remote --exit-code origin >/dev/null 2>&1; then
  echo-run git fetch --prune origin "$GIT_HEAD"
  echo-run git merge --quiet --no-edit "origin/${GIT_HEAD}"
else
  echo-run git merge --quiet --no-edit "$GIT_HEAD"
fi

echo-info "Run 'git reset --hard ${previous_head}' to revert this"

if $push; then
  "${PRIVATE_BIN}/push"
fi
