#!/bin/sh

set -o errexit

echo-warn "This will delete all chezmoi managed dotfiles, chezmoi, and some other files. Commands will be run from the home directory."
echo-warn "You will only be prompted once."

line='
'

cmds="${line}"
cmds="${cmds}cd ${HOME}${line}"
cmds="${cmds}cp -R ${HOME}/.ssh ${HOME}/Downloads/ssh_backup${line}"
cmds="${cmds}chezmoi managed --no-pager | tail -r | tr '\\n' '\\0' | xargs -0 -n1 rm -dv${line}"
cmds="${cmds}rm -fv ${HOME}/.ssh/known_hosts${line}"
cmds="${cmds}rm -rfv"
for f in "$HOME"/.z*; do
  cmds="${cmds} $f"
done
cmds="${cmds}${line}"
cmds="${cmds}chezmoi purge --binary --force --verbose${line}"

safe-eval "$cmds"
