#!/bin/sh

set -o errexit

echo-run op item list --categories "Document" --tags "PGP"
read -p "Which PGP key would you like to import? " -r document_id </dev/tty >&2

if [ -z "$document_id" ]; then
  echo "No document ID passed."
  exit
fi

echo "Checking that ${document_id} exists."
if ! op document get --output /dev/null "$document_id"; then
  exit 1
fi

echo-eval "op document get ${document_id} | gpg --import"
