#!/bin/sh

set -o errexit

url="${1?usage: $0 <url> [<path>]}"
dir="${2:-"$PWD"}"

# TODO: Verify that origin is not set

echo-run cd "$dir"

echo-run git init
echo-run git remote add origin "$url"
echo-run git fetch origin

remote_head="$(cd "$dir" && get-main-branch)"
echo-run git branch -m "$remote_head"
echo-run git reset --mixed "origin/${remote_head}"
