#!/usr/bin/env bash

set -o errexit

if ! in-git-repo; then
  echo-err "Not in a git repository."
  exit 128
fi

head="$(git rev-parse --abbrev-ref HEAD)"

if [[ $head == "HEAD" ]]; then
  echo-err "You are not on the HEAD of a branch."
  exit 1
fi

status="$(git status --porcelain)"

if [[ -n $status ]]; then
  echo-err "There are uncommitted files."
  echo-run git status
  exit 1
fi

if ! git rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' >/dev/null 2>&1; then
  set -- "$@" --set-upstream origin "$head"
fi

args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    -f | --force) args+=(--force-with-lease) ;;
    *) args+=("$1") ;;
  esac
  shift
done

echo-run git push "${args[@]}"
git-show --quiet
