#!/bin/bash

set -o errexit
set -o nounset

USAGE="usage: $(basename "$0") [--max-num=NUM] [COUNT]"

max_id=9999
count=1

while [ $# -gt 0 ]; do
  case "$1" in
    -[[:alnum:]][[:alnum:]]*)
      # Joined short args (e.g. -abc)
      _value="-${1##-?}"
      _arg="${1%%"${1##-?}"}"
      ;;
    --[[:alnum:]]*=*)
      # Args with values separated by an '=' character
      _value="${1#--[[:alnum:]]*=}"
      _arg="${1%%="${_value}"}"
      ;;
  esac
  if [ -n "${_arg:-}${_value:-}" ]; then
    shift
    set -- "$_arg" "$_value" "$@"
  fi
  unset _arg _value

  case "$1" in
    -h | --help)
      echo "$USAGE" >&2
      exit
      ;;
    --max-num)
      max_id="$2"
      shift
      ;;
    -*)
      echo "error: unknown option $1" >&2
      exit 1
      ;;
    *)
      case "$1" in
        ''|*[!0-9]*)
          echo "error: COUNT must be >= 0 (got '$1')" >&2
          exit 1
          ;;
        *) count="$1" ;;
      esac
      ;;
  esac
  shift
done

random_adjective() {
  shuf --echo --head-count=1 \
    "autumn" "hidden" "bitter" "misty" "silent" "empty" \
    "dry" "dark" "summer" "icy" "delicate" "quiet" "white" "cool" "spring" \
    "winter" "patient" "twilight" "dawn" "crimson" "wispy" "weathered" "blue" \
    "billowing" "broken" "cold" "damp" "falling" "frosty" "green" "long" "late" \
    "lingering" "bold" "little" "morning" "muddy" "old" "red" "rough" "still" \
    "small" "sparkling" "throbbing" "shy" "wandering" "withered" "wild" "black" \
    "young" "holy" "solitary" "fragrant" "aged" "snowy" "proud" "floral" \
    "restless" "divine" "polished" "ancient" "purple" "lively" "nameless"
}

random_noun() {
  shuf --echo --head-count=1 \
    "waterfall" "river" "breeze" "moon" "rain" "wind" "sea" \
    "morning" "snow" "lake" "sunset" "pine" "shadow" "leaf" "dawn" "glitter" \
    "forest" "hill" "cloud" "meadow" "sun" "glade" "bird" "brook" "butterfly" \
    "bush" "dew" "dust" "field" "fire" "flower" "firefly" "feather" "grass" \
    "haze" "mountain" "night" "pond" "darkness" "snowflake" "silence" "sound" \
    "sky" "shape" "surf" "thunder" "violet" "water" "wildflower" "wave" "water" \
    "resonance" "sun" "wood" "dream" "cherry" "tree" "fog" "frost" "voice" \
    "paper" "frog" "smoke" "star"
}

generate() {
  adjective="$(random_adjective)"
  noun="$(random_noun)"

  if [ "$max_id" -gt 0 ]; then
    echo "${adjective}-${noun}-$(printf "%0${#max_id}d" "$((RANDOM % (max_id + 1)))")"
    return $?
  fi

  echo "${adjective}-${noun}"
}

i=0
while [ "$i" -lt "$count" ]; do
  generate
  i=$((i+1))
done
