#!/usr/bin/env bash

set -o errexit

eval_cmd="curl --silent https://goteleport.com/download/?os=mac | "
eval_cmd+="egrep --only-matching --no-filename 'https://get.gravitational.com/tsh-\d+.\d+.\d+.pkg' | head -1"

pkg_url="$(FORCE_COLOR=1 echo-eval "$eval_cmd")"

if [ -z "$pkg_url" ]; then
  echo-err "Could not find .pkg URL."
  exit 1
fi

tmp_dir="$(mktemp -d)"

echo-info "Working in ${tmp_dir}"
cd "$tmp_dir"

echo-run curl --proto '=https' --tlsv1.3 --fail --show-error --progress-bar --remote-name "$pkg_url"

pkg_file="$(ls tsh-*.pkg)"

if [ -z "$pkg_file" ] || [ ! -f "$pkg_file" ]; then
  echo-err "Failed to download ${pkg_url}."
  exit 1
fi

echo-run pkgutil --check-signature "$pkg_file"
echo-run sudo installer -pkg "$pkg_file" -target LocalSystem
echo-run tsh version
