#!/bin/sh

safe-run osascript -e '
set theCompletionDate to date "Saturday, April 14, 2022 4:29:04 PM"

tell application "Things3"
  set theList to the selected to dos

  repeat with theToDo in theList
    set the completion date of theToDo to theCompletionDate
  end repeat
end tell'
