#!/bin/sh

set -o errexit

if ! in-git-repo; then
  echo-err "Not in a git repository."
  exit 128
fi

if [ "$#" -eq 0 ]; then
  toplevel="$(git rev-parse --show-toplevel)"
  echo-run git add --verbose "$toplevel"
  exit "$?"
fi

echo-run git add --verbose "$@"
