#!/usr/bin/env bash

set -o errexit

die() {
  [ "$#" -ge 2 ] && echo-err "$2"
  exit "$1"
}

if ! in-git-repo; then
  die 128 "Not in a git repository."
fi

pull=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    -[[:alnum:]][[:alnum:]]*)
      _value="-${1##-?}"
      _arg="${1%%"${1##-?}"}"
      ;;
  esac
  if [ -n "${_arg:-}${_value:-}" ]; then
    shift
    set -- "$_arg" "$_value" "$@"
  fi
  unset _arg _value
  case "$1" in
    -h | --help)
      echo "usage: $(basename "$0") [-p|--pull] [--rebase]"
      exit
      ;;
    -p | --pull) pull=true ;;
    --rebase) rebase=true ;;
    --)
      shift
      break
      ;;
    -?*) die 1 "unknown option: ${1}" ;;
    *) break ;;
  esac
  shift
done

main_branch="$(get-main-branch)"
current_branch="$(git branch --show-current)"

if [ "$current_branch" != "$main_branch" ]; then
  echo-run git switch "$main_branch"
fi

set --

if $rebase; then
  set -- "$@" --rebase
fi

if $pull; then
  echo-run git pull --prune "$@"
fi

git-show --quiet
