#!/bin/sh

set -o errexit
set -o nounset

if ! command -v nosetests >/dev/null 2>&1; then
  echo-err "The 'nosetests' command is not available."
  exit 127
fi

# nose_profile just doesn't work, so lets just get rid of it so we don't always see that error
for nose_profile_dir in "$VIRTUAL_ENV"/lib/python*/site-packages/nose_profile*/; do
  if [ -d "$nose_profile_dir" ]; then
    echo-run rm -rf "$nose_profile_dir"
  fi
done

if ! python -c 'import noseprogressive.result' >/dev/null 2>&1; then
  echo-run pip install nose-progressive
fi

for arg in "$@"; do
  if [ -e "${arg}" ]; then
    set -- "$@" "$arg"
  elif [ -e "${arg%:*}" ]; then
    set -- "$@" "${arg%:*}:${arg##*:}"
  else
    set -- "$@" "$arg"
  fi
  shift
done

set -- --verbose --nologcapture "$@"

TZ=UTC /usr/bin/time -h echo-run nosetests "$@"
