#!/bin/sh

current_branch="$(git rev-parse --abbrev-ref HEAD)"
for branch in $(git for-each-ref --sort=committerdate refs/heads --format='%(refname:short)'); do
  if [ "$branch" = "develop" ] || [ "$branch" = "master" ] || [ "$branch" = "$current_branch" ]; then
    continue
  fi

  git-show --quiet "$branch"
  safe-run git branch -D "$branch" || echo "Not deleting..."

  echo
done
