#!/bin/sh

set -o errexit

die() {
  [ "$#" -ge 2 ] && echo-err "$2"
  exit "$1"
}

if ! in-git-repo; then
  die 128 "Not in a git repository."
fi

pull=false
rebase=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    -[[:alnum:]][[:alnum:]]*)
      _value="-${1##-?}"
      _arg="${1%%"${1##-?}"}"
      ;;
  esac
  if [ -n "${_arg:-}${_value:-}" ]; then
    shift
    set -- "$_arg" "$_value" "$@"
  fi
  unset _arg _value
  case "$1" in
    -h | --help)
      echo "usage: $(basename "$0") [-p|--pull] [--rebase]"
      exit
      ;;
    -p | --pull) pull=true ;;
    --rebase) rebase=true ;;
    --)
      shift
      break
      ;;
    -?*) die 1 "unknown option: ${1}" ;;
    *) break ;;
  esac
  shift
done

main_branch="$(get-main-branch)"
start_point="$(git rev-parse --abbrev-ref --symbolic-full-name "${main_branch}@{upstream}")"
toplevel="$(git rev-parse --show-toplevel)"

# Check if we're in a "worktree" work tree (i.e. not root repository).
if [ -f "${toplevel}/.git" ]; then
  # The main branch name is the wortree directory name + '-main'.
  main_branch="$(basename "${toplevel}")-${main_branch}"
  # Check if the branch exists, creating it if it doesn't.
  if ! git show-ref --quiet --verify "refs/heads/${main_branch}"; then
    # --track=inherit means to copy the upstream configuration of the start-point branch
    # --track=direct means to use the start-point branch itself as the upstream
    echo-run git branch "$main_branch" --track=direct "$start_point"
  fi
fi

current_branch="$(git branch --show-current)"

if [ "$current_branch" != "$main_branch" ]; then
  echo-run git checkout "$main_branch"
fi

set --

if $rebase; then
  set -- "$@" --rebase
fi

if $pull; then
  echo-run git pull --prune "$@"
fi

git-show --quiet
