#!/bin/sh

set -e

if command -v op >/dev/null 2>&1; then
  exit
fi

tmpdir="$(mktemp -d)"
cd "$tmpdir"

VERSION="1.12.3"

if uname | grep -q Darwin; then
  fname="op_apple_universal_v${VERSION}.pkg"
else
  case "$(uname -m)" in
    *arm*) fname="op_linux_arm_v${VERSION}.zip" ;;
    *) fname="op_linux_amd64_v${VERSION}.zip" ;;
  esac
fi

echo-run curl --fail --silent --show-error --location \
  "https://cache.agilebits.com/dist/1P/op/pkg/v${VERSION}/${fname}" \
  -o "$fname"

if uname | grep -q Darwin; then

  echo-run pkgutil --check-signature "$fname"
  echo-run sudo installer -pkg "$fname" -target LocalSystem

else

  echo-run unzip "$fname"

  echo-run gpg \
    --keyserver hkps://keyserver.ubuntu.com \
    --recv-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  echo-run gpg --verify op.sig op

  echo-run sudo mv op /usr/local/bin

fi

echo-run op --version
