#!/usr/bin/env bash

set -o errexit

commit_id="$(git show "$@" --quiet --format="%H")"

if ! git rev-parse "$commit_id" >/dev/null 2>&1; then
  echo "Invalid ref: ${commit_id}"
  exit 1
fi

IFS=$'\n' read -r -d '' -a refs < <(git show-ref --dereference | grep "$commit_id" | cut -d' ' -f2) || true

tags=() heads=()
for ref in "${refs[@]}"; do
  tag="${ref#refs/tags/}"
  tag="${tag%'^{}'}"
  head="${ref#refs/heads/}"
  head="${head#refs/remotes/}"
  if [[ $ref != "$tag" ]]; then
    tags+=("$tag")
  elif [[ $ref != "$head" ]]; then
    heads+=("$head")
  fi
done

header="======== git show --format=\"…\" $* ========"
footer="$(printf '=%.0s' $(seq 1 "${#header}"))"

join_by() {
  local d="${1-}" f="${2-}"
  if shift 2; then
    printf %s "$f" "${@/#/$d}"
  fi
}

git_url="$(git-get-url --with-commit "$commit_id" 2>/dev/null)"

commit_fmt=()
commit_fmt+=("$header")
commit_fmt+=("     Hash: %h")
# Don't use this! It's actually slower than what we do manually above
# commit_fmt+=("   %C(red)Refs:%Creset %D")
commit_fmt+=("     %C(cyan)Tags:%Creset %C(bold)$(join_by ', ' "${tags[@]}")%Creset")
commit_fmt+=("    %C(red)Heads:%Creset $(join_by ', ' "${heads[@]}")")
[[ -n $git_url ]] && commit_fmt+=("      %C(yellow)URL:%Creset ${git_url}")
commit_fmt+=("   %C(green)Author:%Creset %an <%ae>")
commit_fmt+=("%C(green)Committer:%Creset %cn <%ce>")
commit_fmt+=("   %C(blue)A Date:%Creset %ad (%ar)")
commit_fmt+=("   %C(blue)C Date:%Creset %cd (%cr)")
commit_fmt+=("  %C(magenta)Subject:%Creset %C(bold)%s%Creset")
commit_fmt+=("$footer")

# For some reason piping makes git show run way faster (~500ms -> ~20ms)
git show --color=always --format="$(join_by "%Creset%n" "${commit_fmt[@]}")" "$@" | cat
