#!/bin/sh

set -o errexit

push=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h | --help)
      echo "usage: $(basename "$0") [-p|--push]"
      exit
      ;;
    -p | --push)
      push=true
      ;;
    -*)
      echo-err "unknown option: ${1}"
      exit 1
      ;;
    *)
      break
      ;;
  esac
  shift
done

main_branch="$(get-main-branch)"
previous_head="$(git rev-parse --short HEAD)"

if git config remote.origin.url >/dev/null 2>&1; then
  echo-run git fetch --prune origin "$main_branch"
  echo-run git merge --quiet --no-edit "origin/${main_branch}"
else
  echo-run git merge --quiet --no-edit "$main_branch"
fi

echo-info "Run 'git reset --hard ${previous_head}' to revert this"

if $push; then
  "${PRIVATE_BIN}/push"
fi
