#!/bin/sh

echo_array() {
  # shellcheck disable=SC2068
  set -- $@
  len=$#
  num_len="${#len}"
  num=0
  for arg in "$@"; do
    printf "%${num_len}d: %s\n" "$num" "$arg"
    num=$((num + 1))
  done
}

# shellcheck disable=SC2086
IFS=: echo_array ${1:-${PATH}}
