#!/bin/sh

USAGE="usage: $(basename "$0") [key]"

key_id=""

while [ $# -gt 0 ]; do
  case "$1" in
    -h | --help ) echo "$USAGE" ;;
    -)
      echo "error: unknown option ${1}"
      exit 1
      ;;
    *) key_id="$1" ;;
  esac
  shift
done

safe-run gpg --armor --export-secret-keys --export-options export-backup "$key_id"
