#!/bin/sh

usage="Wrapper for chezmoi.

Usage:
  $(basename "$0") -h | --help            Show usage and exit.
  $(basename "$0") apply [-y|--yes|--noconfirm]  Show a diff and apply changes.
  $(basename "$0") <any chezmoi command>  Passthrough to chezmoi.
"

command="$1"
if [ -z "$command" ]; then
  echo "$usage"
  exit 1
fi

shift

case "$command" in
  -h | --help)
    echo "$usage"
    exit
    ;;
  apply)
    cmd="safe-run"

    # POSIX sh way to remove arguments from the list
    for arg; do
      shift
      case $arg in
        --noconfirm | --yes | -y)
          cmd="echo-run"
          ;;
        *) set -- "$@" "$arg" ;;
      esac
    done

    if [ "$cmd" = "safe-run" ] && echo-run chezmoi verify "$@"; then
      echo-info "Nothing to apply."
      exit
    fi
    if ! echo-run chezmoi diff --no-pager "$@"; then
      echo-warn "Error showing diff. Are you signed in to 1Password?"
      exit 1
    fi
    if ! "$cmd" chezmoi apply "$@"; then
      echo-info "You can run 'dotfiles add <file>...' to update the source."
      exit
    fi
    ;;
  save)
    save -C "$(chezmoi source-path)" "$@"
    ;;
  *)
    echo-run chezmoi "$command" "$@"
    ;;
esac
