#!/bin/sh

printf "Getting remote HEAD... "
GIT_HEAD="$(get-remote-head)"
echo "$GIT_HEAD"

if [ "$(git rev-parse --abbrev-ref HEAD)" = "${GIT_HEAD}" ]; then
  echo-run git fetch origin "${GIT_HEAD}"
  echo-run git merge --ff-only
else
  echo-run git fetch origin "${GIT_HEAD}:${GIT_HEAD}"
fi

"${PRIVATE_BIN}/git-show" --quiet "${GIT_HEAD}"
