#!/bin/sh

set -o errexit

USAGE="usage: $(basename "$0") [--key KEY] [--document ID]"

key_id=""
document_id=""

while [ $# -gt 0 ]; do
  case "$1" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
    --key)
      key_id="$2"
      shift
      ;;
    --document)
      document_id="$2"
      shift
      ;;
    *)
      echo "error: unknown option ${1}"
      echo "$USAGE"
      exit 1
      ;;
  esac
  shift
done

if [ -z "$key_id" ]; then
  echo-run gpg --list-secret-keys
  printf "Which PGP secret key would you like to export to 1Password? "
  read -r key_id </dev/tty >&2
fi

if ! gpg --list-secret-keys "$key_id" >/dev/null; then
  exit 1
fi

if [ -z "$document_id" ]; then
  echo-run op item list --categories Document --tags PGP
  printf "Which document would you like to update? "
  read -r document_id </dev/tty >&2
fi

echo "Checking that ${document_id} exists."
if ! op document get --output /dev/null "$document_id"; then
  exit 1
fi

echo-run gpg --list-secret-keys "$key_id"
echo-run op item get "$document_id"
safe-eval "gpg --armor --export-secret-keys --export-options export-backup '${key_id}' | op document edit --file-name 'Secret Key.asc' ${document_id} -"
