#!/bin/sh

USAGE="usage: $(basename "$0") [FILE...]"

for arg in "$@"; do
  case "$arg" in
    -h | --help)
      echo "$USAGE" >&2
      exit
      ;;
  esac
done

if [ $# -eq 0 ]; then
  echo "$USAGE" >&2
  exit 1
fi

if ! python -c 'import autoflake' >/dev/null 2>&1; then
  echo-run pip install autoflake
fi

echo-run autoflake --remove-all-unused-imports --in-place "$@"
