#!/bin/sh

set -o errexit

die() {
  [ "$#" -ge 2 ] && echo-err "$2" >&2
  exit "$1"
}

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  die 1 "Not a git repository."
fi

commit=false
commit_id=

while [ "$#" -gt 0 ]; do
  case "$1" in
    -[[:alnum:]][[:alnum:]]*)
      _value="-${1##-?}"
      _arg="${1%%"${1##-?}"}"
      ;;
  esac
  if [ -n "${_arg:-}${_value:-}" ]; then
    shift
    set -- "$_arg" "$_value" "$@"
  fi
  unset _arg _value
  case "$1" in
    -h | --help)
      echo "usage: $(basename "$0") [-c|--commit]"
      exit
      ;;
    -c | --commit)
      commit=true
      ;;
    --with-commit)
      if [ $# -lt 2 ]; then
        die 1 "${1} requires a value"
      fi
      commit=true
      commit_id="$2"
      shift
      ;;
    --)
      shift
      break
      ;;
    -?*) die 1 "unknown option: ${1}" ;;
    *) break ;;
  esac
  shift
done

default_remote="origin"
giturl="$(git ls-remote --get-url "$default_remote")"

if [ -z "$giturl" ]; then
  die 1 "Git remote is not set for ${default_remote}"
fi

project_url="$(echo "$giturl" | sed "s~:~/~" | sed "s~git@~https://~" | sed "s~\.git~~")"

if $commit; then
  if [ -z "$commit_id" ]; then
    commit_id="$(git rev-parse HEAD)"
  fi
  echo "${project_url}/commit/${commit_id}"
  exit $?
fi

echo "$project_url"
