#!/bin/sh

USAGE="usage: $(basename "$0") [-l|--latest|-p|--pull] <branch name>"

set -o errexit

branch_name=
latest=false
stash=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
    -l | --latest | -p | --pull)
      latest=true
      ;;
    --stash)
      stash=true
      ;;
    --)
      shift
      break
      ;;
    -?*)
      echo "unknown option: ${1}"
      exit 1
      ;;
    *)
      branch_name="$1"
      ;;
  esac
  shift
done

if [ -z "$branch_name" ]; then
  echo-err "missing branch name" >&2
  exit 1
fi

main_branch="$(get-main-branch)"

if $latest; then
  echo-run git fetch origin "$main_branch"
fi

stashed=false
if $stash; then
  if [ -n "$(git status --porcelain)" ]; then
    stashed=true
    echo-run git stash
  fi
fi

set +o errexit
echo-run git switch --no-track --create "$branch_name" "origin/${main_branch}"
exit_code=$?
set -o errexit

if $stashed; then
  echo-run git stash pop
fi

exit "$exit_code"
