#!/usr/bin/env bash

set -o errexit

USAGE="usage: $(basename "$0") SEARCH_REGEX REPLACE"

die() {
  [ "$#" -ge 2 ] && echo-err "$2"
  exit "$1"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -[[:alnum:]][[:alnum:]]*)
      _value="-${1##-?}"
      _arg="${1%%"${1##-?}"}"
      ;;
  esac
  if [ -n "${_arg:-}${_value:-}" ]; then
    shift
    set -- "$_arg" "$_value" "$@"
  fi
  unset _arg _value
  case "$1" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
    --)
      shift
      break
      ;;
    -?*) die 1 "unknown option: ${1}" ;;
    *) break ;;
  esac
  shift
done

if [ $# -lt 2 ]; then
  die 1 "Not enough arguments"
fi

if [ $# -gt 2 ]; then
  die 1 "Too many arguments"
fi

safe-eval "rg '${1}' --files-with-matches | xargs -n 1 -o echo-run sed -i '' 's/${1}/${2}/g'"
