#!/bin/sh

set -o errexit

upgrade_path() {
  # $1: Path to a python executable
  case "${1##*/}" in
    pip | pip[[:alnum:]] | pip[[:alnum:]].[[:alnum:]])
      echo-run "$1" install --upgrade pip
      ;;
    python | python[[:alnum:]] | python[[:alnum:]].[[:alnum:]])
      echo-run "$1" -m pip install --upgrade pip
      ;;
  esac
}

USAGE="usage: $(basename "$0") [path...]"

for arg in "$@"; do
  case "$arg" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
  esac
done

# Assume arguments are paths to python/pip executables or directories
# containing python/pip executables.
if [ $# -gt 0 ]; then
  for arg in "$@"; do

    # If a specific file was passed assume it's a python or pip executable and
    # upgrade it.
    if [ ! -d "$arg" ]; then
      upgrade_path "$arg"
    fi

    # Remove any trailing slash to prevent a double slash//.
    arg="${arg%/}"
    for f in "$arg"/python*; do
      if [ -r "$f" ]; then
        upgrade_path "$f"
      fi
    done
  done
  exit
fi

set -f
IFS=:
for d in $PATH; do
  set +f
  if [ -z "$d" ]; then
    d="."
  fi
  for f in "$d"/python*; do
    if [ -r "$f" ]; then
      upgrade_path "$f"
    fi
  done
  # for f in "$d"/.[!.]* "$d"/..?* "$d"/*; do
  #   if [ -x "$f" ] && [ ! -h "$f" ]; then
  #     case "${f##*/}" in
  #       python | python[[:alnum:]] | python[[:alnum:]].[[:alnum:]])
  #         echo-run "$f" -m pip install --upgrade pip
  #         ;;
  #     esac
  #   fi
  # done
done
