#!/usr/bin/env bash

NEWLINE="
"

if [ -p /dev/stdin ]; then
  while read -r line; do
    pyobj+="${line}${NEWLINE}"
  done
  pyobj+="$line"
else
  pyobj="$*"
fi

from_clipboard=false
if [[ -z $pyobj ]]; then
  pyobj="$(pbpaste)"
  from_clipboard=true
fi

if [[ -z $pyobj ]]; then
  exit
fi

# The `-` means read from stdin
output="$(
  python3 - <<EOF
import json
import datetime
try:
    obj = $pyobj
    print(json.dumps(obj, indent=2, default=str))
except Exception as e:
    print('Error parsing python object')
    print(e)
EOF
)"

if $from_clipboard; then
  echo "$output" | pbcopy
fi

echo "$output"
