#!/bin/sh

set -o errexit


die() {
  [ "$#" -ge 2 ] && echo-err "$2" >&2
  exit "$1"
}

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  die 1 "Not a git repository."
fi

url="$(git-get-url "$@")"

if [ -z "$url" ]; then
  die 1 "No URL found."
fi

echo-run open "$url"
