#!/bin/sh

set -o errexit

# Make sure we're in a git branch
git branch >/dev/null

branch="$(git for-each-ref --sort=-committerdate --color=always refs/heads/ --format='%(HEAD) %(color:green)%(refname:short)%(color:reset) - %(contents:subject) - %(color:yellow)%(committerdate:relative)%(color:reset)' | fzf --no-multi --delimiter ' - ' --preview='git show --color=always {-1}' --ansi)"
branch="${branch%% - *}"
branch="${branch##\* }"
branch="${branch##  }"
echo-run git switch "$branch" || exit $?
git-show --quiet
