#!/bin/sh

if ! in-git-repo; then
  exit 128
fi

GIT_HEAD="$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@')" 2>/dev/null
if [ -z "$GIT_HEAD" ]; then
  GIT_HEAD="$(git remote show origin 2>&1 | grep 'HEAD branch' | cut -d ':' -f 2 | cut -d ' ' -f 2)"
fi
if [ -z "$GIT_HEAD" ]; then
  GIT_HEAD="$(git config --get init.defaultBranch)"
fi
echo "${GIT_HEAD:-main}"
