#!/bin/sh

set -o errexit

die() {
  [ "$#" -ge 2 ] && echo-err "$2" >&2
  exit "$1"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h | --help)
      echo "usage: $(basename "$0") <repository url>"
      exit
      ;;
    --)
      shift
      break
      ;;
    -?*) die 1 "unknown option: ${1}" ;;
    *) break ;;
  esac
  shift
done

repository_url="$1"

if [ -z "$repository_url" ]; then
  die 1 "No repository URL passed."
fi

echo-run git init
echo-run git remote add origin "$repository_url"
echo-run git fetch origin

printf "Getting remote HEAD... "
head="$(get-main-branch)"
echo "$head"

safe-run git reset --hard origin/"$head"
safe-run git checkout -b "$head" --track origin/"$head"
