#!/bin/sh

set -o errexit

USAGE="usage: $(basename "$0") [-p|--push] [-s|--pull] [-f|--force] [-n|--no-verify] [<commit message>]"

die() {
  [ "$#" -ge 2 ] && echo-err "$2"
  exit "$1"
}

pull=false
push=false
message=''
force=false
no_verify=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    -[[:alnum:]][[:alnum:]]*)
      _value="-${1##-?}"
      _arg="${1%%"${1##-?}"}"
      ;;
  esac
  if [ -n "${_arg:-}${_value:-}" ]; then
    shift
    set -- "$_arg" "$_value" "$@"
  fi
  unset _arg _value
  case "$1" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
    -f | --force)
      force=true
      ;;
    -p | --push)
      push=true
      ;;
    -s | --pull)
      # s: sync
      pull=true
      ;;
    -n | --no-verify)
      no_verify=true
      ;;
    -*)
      echo-err "unknown option: ${1}"
      exit 1
      ;;
    *)
      if [ -n "$message" ]; then
        echo-err "unexpected argument: ${1}"
        exit 1
      fi
      message="$1"
      ;;
  esac
  shift
done

set --

add

status="$(git status --porcelain)"

if [ -z "$status" ] && [ -n "$message" ]; then
  echo-err "There are no changes so we can't create your commit: ${message}"
  exit 1
fi

if [ -n "$status" ]; then
  echo-info "Undo these changes with 'git reset $(git rev-parse --short HEAD)'"

  set --
  if $no_verify; then
    set -- "$@" --no-verify
  fi
  if [ -n "$message" ]; then
    set -- "$@" --message "$message"
  fi

  echo-run git commit "$@" || die $? "Failed to create a commit. Fix any errors and retry."
else
  echo-info "Skipping commit since there were no changes."
fi

if $push; then
  if git rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' >/dev/null 2>&1 && $pull; then
    echo-run git pull --rebase
  fi

  set --
  if $force; then
    set -- "$@" --force
  fi

  push "$@"
fi
