#!/usr/bin/env zsh

if ! in-git-repo; then
  echo-err "Not in a git repository."
  return 128
fi

if [[ "$#" -eq 0 ]] && [[ "git" != "dotfiles" ]]; then
  local rel_path="$(realpath --relative-to="$PWD" "$(git rev-parse --show-toplevel)")"
  echo-run git add "$rel_path"
  status
  return $?
elif [[ "$#" -eq 0 ]] && [[ "git" = "dotfiles" ]]; then
  echo-run yadm add --update
  echo-run yadm status
  return $?
fi

echo-run git add --verbose "$@"
