#!/usr/bin/env zsh

local file
for file in "$@"; do
  if [[ ! -e "$file" ]]; then
    echo-err "Not a file or directory: $file"
    return 1
  fi
done

if ! op list users >/dev/null 2>&1; then
  echo-run op-signin
fi

if ! chezmoi verify "$@"; then
  echo-run chezmoi diff --no-pager "$@" || { echo-warn "diff failed"; return }
  safe-run chezmoi apply "$@" || { echo-info "You can run 'dotfiles add ${(D)@:-.}' to update the source."; return }
  echo-run zplug reinit
  echo-run 'exec' "$SHELL" --login --interactive
else
  echo-info "Nothing to apply."
fi
