#!/usr/bin/env zsh

local host line
ping "$@" | while read line; do
  if [[ "$line" != "${line//*time=}" ]]; then
    echo "$host: ${line//*time=}"
  elif [[ "$line" != "${line//PING*}" ]]; then
    if [[ "${${(@s/ /)line}[2]}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      host="${${(@s/ /)line}[2]}"
    else
      host="${${${(@s/ /)line}[2,3]}[1,-2]}"
    fi
  fi
done
