#!/usr/bin/env zsh

local cmd="git"
if ! in-git-repo; then
  echo "Not in git repository. Using dotfiles."
  cmd="dotfiles"
fi

echo-run $cmd status "$@"

# if needs_git_cleanup; then
#   git_cleanup
# fi
