#!/bin/sh

if ! command -v "locale-gen" >/dev/null 2>&1; then
  # shellcheck disable=SC2016
  echo-err 'locale-gen is not in $PATH'
  exit 127
fi

set -o errexit
set -o xtrace

sudo perl -pi -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
sudo locale-gen en_US.UTF-8
sudo update-locale en_US.UTF-8
