#!/bin/sh

set -o errexit

if ! in-git-repo; then
  echo-err "Not in a git repository."
  return 128
fi

printf "Getting remote HEAD... "
head="$(get-remote-head)"
echo "$head"

echo-run git switch "$head"
echo-run git fetch --prune origin "$head"
echo-run git rebase origin "$head"
git-show --quiet
