#!/usr/bin/env bash

set -o errexit

eval_cmd="curl --silent https://mattermost.com/download/ | "
eval_cmd+="grep --only-matching --no-filename 'https://releases.mattermost.com/desktop/.*/mattermost-desktop-.*-mac.dmg'"

dmg_url="$(FORCE_COLOR=1 echo-eval "$eval_cmd")"

if [[ -z "$dmg_url" ]]; then
  echo-err "Could not find dmg url"
  exit 1
fi

tmp_dir="$(mktemp -d)"

echo-info "Working in ${tmp_dir}"
cd "$tmp_dir"

echo-run curl --progress-bar --remote-name "$dmg_url"

dmg_file="$(ls mattermost-desktop-*-mac.dmg)"

if [[ -z "$dmg_file" ]]; then
  echo-err "Failed to download ${dmg_url}"
  exit 1
fi

for volume in /Volumes/Mattermost*; do
  if [[ -d "$volume" ]]; then
    echo-run hdiutil detach "$volume"
  fi
done

echo-run hdiutil attach -quiet "$dmg_file"

cd /Volumes/Mattermost*

if [[ -d "/Applications/Mattermost.app" ]]; then
  echo-run rm -rf /Applications/Mattermost.app
fi

echo-run cp -R "${PWD}/Mattermost.app" /Applications

# Need to cd out of the directory so it's not in use when we detach
cd - >/dev/null

for volume in /Volumes/Mattermost*; do
  echo-run hdiutil detach "$volume"
done
