#!/usr/bin/env bash

USAGE="usage: $(basename "$0") [--recent] [--after=<date>] [--] [<path>]"

recent=false
after=

while [ "$#" -gt 0 ]; do
  case "$1" in
    --[[:alnum:]]*=*)
      _value="${1#--[[:alnum:]]*=}"
      _arg="${1%%=${_value}}"
      ;;
  esac
  if [ -n "${_arg:-}${_value:-}" ]; then
    shift
    set -- "$_arg" "$_value" "$@"
  fi
  unset _arg _value
  case "$1" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
    --after)
      after="$2"
      shift
      ;;
    --recent) recent=true ;;
    --) break ;;
    -?*)
      echo-err "unknown option: ${1}" >&2
      exit 1
      ;;
    *) break ;;
  esac
  shift
done

if $recent; then
  set -- --after="$(date -v-6m +%Y-%m-%d)" "$@"
elif [ -n "$after" ]; then
  set -- --after="$after" "$@"
fi

newline=$'\n'
header="Count|Engineer|Oldest|Newest"
output=""
current_name=""
current_count=""
oldest=""
latest=""

while IFS= read -r line; do
  if [[ "${#line}" -lt 1 ]]; then
    output+="${current_count}|${current_name}|${oldest}|${latest}${newline}"
    current_name=""
    current_count=""
    oldest=""
    latest=""
  elif [[ "$line" =~ ^\ +([0-9]{4}-[0-9]{2}-[0-9]{2})$ ]]; then
    if [[ -z "$latest" ]]; then
      oldest="${BASH_REMATCH[1]}"
      latest="${BASH_REMATCH[1]}"
    else
      oldest="${BASH_REMATCH[1]}"
    fi
  elif [[ "$line" =~ ^(.*)\ \(([0-9]+)\).*$ ]]; then
    current_name="${BASH_REMATCH[1]}"
    current_count="${BASH_REMATCH[2]}"
  fi

done <<<"$(git --no-pager shortlog --no-merges --reverse --email --pretty=format:%as --numbered "$@")"

echo "${header}${newline}${output}" | column -t -s '|'
