#!/bin/sh

file="${HOME}/.ssh/id_rsa.pub"
if [ ! -f "$file" ]; then
  file="${HOME}/.ssh/id_ed25519.pub"
fi
if [ ! -f "$file" ]; then
  echo-err "Failed to find public key file in ${HOME}/.ssh" >&2
  exit 1
fi
pbcopy < "$file" | echo-ok 'Public key copied to clipboard.'
