#!/bin/sh

set -o errexit

USAGE="usage: $(basename "$0") [-d|--disconnect] <VPN name>"
vpn_name=''

while [ $# -ge 1 ]; do
  case "$1" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
    -d | --disconnect)
      scutil --nc list | grep Connected 2>&1 | cut -d '"' -f 2 | \
        while read -r; do
          echo-run networksetup -disconnectpppoeservice "$REPLY"
        done
      echo-ok "Disconnected from all VPNs"
      exit $?
      ;;
    --)
      shift
      vpn_name="$*"
      break
      ;;
    -*)
      echo-err "unknown option: ${1}"
      exit 1
      ;;
    *)
      vpn_name="$1"
  esac
  shift
done

if [ -z "$vpn_name" ]; then
  echo-err "A VPN name is required"
  exit 1
fi

if ! scutil --nc list | cut -d '"' -f 2 | grep -q "$vpn_name"; then
  echo-err "'${vpn_name}' is not a valid VPN"
  exit 1
fi

is_connected() {
  networksetup -showpppoestatus "$vpn_name" | grep -q "^connected$"
}

if ! is_connected; then
  echo-run networksetup -connectpppoeservice "$vpn_name"
fi

timeout="$(date -v+5S '+%s')"
until is_connected || [ "$(date '+%s')" -gt "$timeout" ]; do
  sleep 0.5
done

if ! is_connected; then
  echo-err "Timed out connecting to VPN"
  exit 1
fi

echo-ok "Connected to VPN"
