#!/bin/sh

for ref in $(git for-each-ref --sort=committerdate refs/remotes/origin \
  --format='%(authoremail) %(refname)' |
  grep "$(git config user.email)" \
    grep origin |
  cut -d ' ' -f 2); do
  branch="${ref##refs\/remotes\/origin\/}"
  if [ "$branch" = "develop" ] || [ "$branch" = "master" ] || [ "$branch" = "HEAD" ]; then
    continue
  fi

  git-show --quiet "refs/remotes/origin/$branch"
  safe-run git push origin --delete "$branch" || echo "Not deleting..."

  echo
done
