#!/bin/sh

if ! command -v apt-get >/dev/null 2>&1; then
  echo-err "apt-get is not in \$PATH"
  exit 127
fi

if ! sudo true; then
  echo "Skipping Ubuntu packages install because we don't have sudo permissions"
  exit
fi

set -e

# shellcheck source=.profile
. "${HOME}/.profile"

echo-run sudo apt --quiet --quiet --yes update
echo-run sudo apt --quiet --quiet --yes install shellcheck vim neovim git python3-pip
