#!/usr/bin/env bash

if [ -p /dev/stdin ]; then
  while read -r line; do
    pyobj+="$line\n"
  done
  pyobj+="$line"
else
  pyobj="$*"
fi

from_clipboard
if [[ -z "$pyobj" ]]; then
  pyobj="$(pbpaste)"
  from_clipboard=1
fi

if [[ -z "$pyobj" ]]; then
  exit
fi

# The `-` means read from stdin
output="$(python3 - << EOF
import json
try:
    obj = $pyobj
    print(json.dumps(obj, indent=2))
except Exception as e:
    print('Error parsing python object')
    print(e)
EOF
)"

if [[ -n "$from_clipboard" ]]; then
  echo "$output" | pbcopy
fi

echo "$output"
