#!/bin/sh

set -o errexit

for arg in "$@"; do
  case "$arg" in
    -h | --help )
      echo "usage: arc-rebase [branch]"
      exit
      ;;
  esac
done

if [ $# -eq 1 ]; then
  rebase "$1"
  arc-diff -am "Rebase off '$1'"
else
  rebase
  arc-diff -am "Rebase"
fi
