#!/usr/bin/env bash

if ! in-git-repo; then
  echo-err "Not in a git repository."
  exit 128
fi

head="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$head" == "HEAD" ]]; then
  echo-err "You are not on the HEAD of a branch."
  exit 1
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo-err "There are uncommitted files."
  echo-run git status
  exit 1
fi

remote="$(git rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>/dev/null)"
if [[ -z "$remote" ]]; then
  set -- "$@" --set-upstream origin "$head"
fi

args=()
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -f | --force) args+=(--force-with-lease) ;;
    *) args+=("$1") ;;
  esac
  shift
done

echo-run git push "${args[@]}"
