#!/bin/sh

USAGE="usage: $(basename "$0") <path> [<path>...] -- <git args>"

if [ $# -eq 0 ]; then
  echo "$USAGE"
  exit 1
fi

for arg in "$@"; do
  case "$arg" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
    --)
      break
      ;;
  esac
done

PATHS=""

while [ "$#" -gt 0 ]; do
  path="$1"
  shift
  if [ "$path" = "--" ]; then
    break
  fi
  full_path="$(cd "$(dirname "$path")" || exit; pwd)/$(basename "$path")"
  if ! git -C "$full_path" rev-parse --git-dir >/dev/null 2>&1; then
    continue
  fi
  PATHS="${PATHS} ${full_path}"
done

for full_path in $PATHS; do
  echo-run git -C "$full_path" "$@"
done
