name: 'Setup chezmoi'
description: 'Install chezmoi and move source files to home directory'
runs:
  using: "composite"
  steps:
    - name: Run
      shell: bash
      run: |
        set -x
        export BINDIR="${HOME}/.chezmoi/bin"
        export PATH="${PATH}:${BINDIR}"
        mkdir -p "${BINDIR}"
        set +x
        sh -c "$(curl -fsLS git.io/chezmoi)"
        set -x
        if [ -n "$GITHUB_PATH" ]; then
          echo Adding ${BINDIR} to ${GITHUB_PATH}
          echo $BINDIR >> "$GITHUB_PATH"
        else
          echo ::add-path::${BINDIR}
        fi
        rm -rf "$(chezmoi source-path)"
        mkdir -p "$(dirname $(chezmoi source-path))"
        cp -r "$GITHUB_WORKSPACE" "$(chezmoi source-path)"
        chezmoi init --no-tty
        chezmoi apply --no-tty --exclude=scripts
