name: 'Setup chezmoi'
description: 'Install chezmoi and move source files to home directory'
runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        sh -c "$(curl -fsLS git.io/chezmoi)"
        if [ -n "$GITHUB_PATH" ]; then
          echo Adding ${BINDIR} to ${GITHUB_PATH}
          echo $BINDIR >> "$GITHUB_PATH"
        else
          echo ::add-path::${BINDIR}
        fi
      env:
        BINDIR: ${HOME}/.chezmoi_bin
    - name: Copy repository to chezmoi
      shell: bash
      run: |
        set -x
        rm -rf "$(chezmoi source-path)"
        mkdir -p "$(dirname $(chezmoi source-path))"
        cp -r "$GITHUB_WORKSPACE" "$(chezmoi source-path)"
        chezmoi init --no-tty
        chezmoi apply --no-tty --exclude=scripts
