#!/bin/sh

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  exit 128
fi

# Try and get origin's HEAD first.
symbolic_ref="$(git symbolic-ref --short --quiet refs/remotes/origin/HEAD)"
main_branch_candidate="$(basename "$symbolic_ref")"

# If we failed to get the symbolic ref for refs/remotes/origin/HEAD...
if [ -z "$main_branch_candidate" ]; then
  # ... and there's an origin, we may just need to set-head first. I've seen
  # this happen in Codespaces
  if git remote get-url origin >/dev/null 2>&1; then
    git remote set-head --auto origin >/dev/null 2>&1
  fi

  # Then try and get the symbolic ref for origin/HEAD again.
  symbolic_ref="$(git symbolic-ref --short --quiet refs/remotes/origin/HEAD)"
  main_branch_candidate="$(basename "$symbolic_ref")"
fi

# If there's only one branch, that's the main branch.
if [ -z "$main_branch_candidate" ] && git rev-parse --abbrev-ref --branches | wc -l | grep -E -q '^\s*1$'; then
  main_branch_candidate="$(git rev-parse --abbrev-ref --branches)"
fi

# If there are no actual branches, then the symbolic-ref for HEAD is the main
# branch. This seems like it can only happen on a brand new repository, when
# there aren't any actual commits yet.
if [ -z "$main_branch_candidate" ] && git rev-parse --abbrev-ref --branches | wc -l | grep -E -q '^\s*0$'; then
  main_branch_candidate="$(git symbolic-ref --short --quiet HEAD)"
fi

# Use the configured defaultBranch.
if [ -z "$main_branch_candidate" ]; then
  main_branch_candidate="$(git config --get init.defaultBranch)"
fi

# If all else fails, fallback to "main" as the main branch name.
echo "${main_branch_candidate:-main}"
