#!/bin/sh

set -o errexit
set -o nounset

USAGE="usage: $(basename "$0") [-h|--help] INSTALLER..."

for arg; do
  case "$arg" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
  esac
done

if [ "$#" -eq 0 ]; then
  echo "$USAGE" >&2
  exit 1
fi

homebrew_install() {
  if command -v brew >/dev/null 2>&1; then
    echo-run brew install "$1"
  else
    echo "error: unable to install ${1} (need homebrew installed)" >&2
    exit 1
  fi
}

for installer in "$@"; do
  if command -v "install-${installer}" >/dev/null 2>&1; then
    echo-run "install-${installer}"
    continue
  fi

  case "$installer" in
    just) homebrew_install just ;;
    shfmt) homebrew_install shfmt ;;
    *)
      echo "error: unable to install ${installer}" >&2
      exit 1
      ;;
  esac
done
