#!/bin/sh

set -o errexit
set -o nounset

USAGE="usage: $(basename "$0") [-h|--help]"

while [ $# -gt 0 ]; do
  case "$1" in
    -h | --help)
      echo "$USAGE" >&2
      exit
      ;;
  esac
  shift
done

branch_name="$(git branch --show-current)"

if [ -z "$branch_name" ]; then
  echo "error: not on a branch" >&2
  exit 1
fi

echo-run git fetch --prune origin "${branch_name}"
safe-run git reset --hard "origin/${branch_name}"
