#!/bin/sh

if [ $# -eq 0 ]; then
  exec echo-run gh codespace ssh
fi

case "$1" in
  create)
    if git config --get remote.origin.url >/dev/null 2>&1; then
      url="$(git config --get remote.origin.url)"
      url="${url##git@github.com:}"
      url="${url%.git}"
      case "$url" in
        :*) : ;;
        */*) set -- --repo "$url" "$@" ;;
      esac
    fi
    ;;
esac

exec echo-run gh codespace "$@"
