#!/bin/sh

set -e

# shellcheck source=.profile
. "${HOME}/.profile"

echo-run brew tap "georgewitteman/tap"
echo-run brew update

brew bundle --verbose --no-lock --file=- <<-EOF
brew "fd"
brew "fzf"
brew "gnupg"
brew "htop"
brew "hyperfine"
brew "jq"
brew "pinentry-mac"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "starship"
brew "terraform"
brew "tmux"
brew "tree"
brew "universal-ctags"
brew "vim"
brew "wget"
EOF

if ! command -v "aws" >/dev/null 2>&1; then
  echo-run brew install awscli
fi

if ! ls /usr/local/Cellar/*openssl*; then
  echo-run brew install openssl
fi
