#!/usr/bin/env zsh

if [[ "$VIRTUAL_ENV" != "" ]]; then
  echo -n "${fg[red]}"
  echo "Warning:${reset_color} It's dangerous to run brew from within a virtual environment."
  echo "         See https://docs.brew.sh/Homebrew-and-Python for more info."
  return 1
fi

command brew "$@"
local ret="$status"

if [[ "$1" = "install" || "$1" = "upgrade" || "$1" = "uninstall" ]]; then
  zplug reinit
fi

if [[ "$1" = "install" ]]; then
  echo
  echo-info "Don't forget to add this to bootstrap_macos."
elif [[ "$1" = "uninstall" ]]; then
  echo
  echo-info "Don't forget to remove this from bootstrap_macos."
fi

return $ret
