#!/usr/bin/env zsh

if [[ -z "${OP_SESSION_my:-}" ]]; then
  echo-eval 'eval "$(op signin)"' || return "$?"
fi

case "$1" in
  'cd')
    shift
    echo-run cd "$(chezmoi source-path "$@")"
    ;;
  *)
    command dotfiles "$@"
    ;;
esac
