#!/usr/bin/env zsh

echo-run zplug reinit

if [[ -n "$(jobs)" ]]; then
  echo-warn "Current shell has backgrounded jobs. Not restarting ${SHELL}."
  return 1
fi

echo-eval 'path=(); fpath=()'
echo-run exec "$SHELL" --login --interactive
