#!/usr/bin/env zsh

local compdump_file="$1"

if [[ -z "$compdump_file" ]]; then
  echo-err "Usage: ${0:t} <compdump file>"
  return 1
fi

[[ -f "$compdump_file.zwc" ]] && echo-run rm -f "$compdump_file.zwc"

local zfile
for zfile in ${ZDOTDIR:-${HOME}}/.z(shenv|profile|shrc|login|logout)(N-.); do
  echo-run rm -f "${zfile}.zwc" || return 1
done
