#!/usr/bin/env zsh

if [[ -z "$1" ]] ; then
  echo "usage: ${0:t} <venv name>" >&2
  return 1
fi

local venv_dir="${1:a}"
until [[ "${venv_dir}" = "/" || -f "${venv_dir}/${1}/bin/activate" ]]; do
  venv_dir="${venv_dir:h}"
done

local venv_path

if [[ -f "${venv_dir}/${1}/bin/activate" ]]; then
  venv_path="${venv_dir}/${1}"
  venv_path="${venv_path:a}"
else
  echo "Couldn't find a valid venv for '${1}'"
  return 1
fi

if [[ -n "$VIRTUAL_ENV" ]] && [[ "$VIRTUAL_ENV" = "${venv_path}" ]]; then
  # Already in venv
  return
fi

if [[ -n "$VIRTUAL_ENV" ]]; then
  # In a different virtual_env
  save-virtual-env
fi

echo-run source "${venv_path}/bin/activate"
