#!/usr/bin/env zsh

if ! is-clean-repo; then
  echo "The repository needs to be clean."
  status
  return 1
fi

local arc_args=()

echo -n "Getting remote HEAD... "
local git_head="$(get-remote-head)"
echo $git_head

arc_args+=('--onto' "${git_head}")

if [[ "$1" =~ "^D[0-9]+$" ]]; then
  arc_args+=('--revision' "$1")
  shift
fi

echo-run arc land "${arc_args[@]}" "$@"
