#!/usr/bin/env zsh

if ! is-clean-repo; then
  echo "The repository needs to be clean."
  status
  return 1
fi

if [[ "$#" -eq 0 ]]; then
  echo -n "Getting remote HEAD... "
  GIT_HEAD="$(get-remote-head)"
  echo $GIT_HEAD

  echo-run arc land --onto "$GIT_HEAD"
elif [[ "$1" =~ "^D[0-9]+$" ]]; then
  echo -n "Getting remote HEAD... "
  GIT_HEAD="$(get-remote-head)"
  echo $GIT_HEAD

  echo-run arc land "${@[2,-1]}" --revision "$1" --onto "$GIT_HEAD"
else
  echo-run arc land "$@"
fi
