#!/usr/bin/env zsh

local file managed_files=() files_to_rm=()
managed_files=("${(@f)$(chezmoi managed)}")
for file in "${managed_files[@]}"; do
  if [[ ! -e "$file" ]]; then
    local source_file="$(chezmoi source-path "$file")"
    if [[ "${source_file/%.tmpl/}" = "$source_file" ]]; then
      files_to_rm+=("$file")
    fi
  fi
done

if [[ "${#files_to_rm}" -ne 0 ]]; then
  echo-run chezmoi rm "${files_to_rm[@]}"
else
  echo "Nothing to remove."
fi

if ! chezmoi verify; then
  echo-run chezmoi diff --no-pager
  safe-run chezmoi apply
fi
