#!/usr/bin/env zsh

if [[ "$1" == "" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
  echo "Usage: ${0:t} <file> [-h|--help]"
  exit 1
fi

if [ -f "$1" ]; then
  case "$1" in
    *.dmg) echo_run hdiutil mount "$1" ;;
    *.tar) echo_run tar -xvf "$1" ;;
    *.zip) echo_run unzip "$1" ;;
    *.ZIP) echo_run unzip "$1" ;;
    *.pax) echo_run pax -r < "$1" ;;
    *.pax.Z) echo_run uncompress "$1" --stdout | pax -r ;;
    *.rar) echo_run unrar x "$1" ;;
    *.7z) echo_run 7z x "$1" ;;
    *.xar) echo_run xar -xvf "$1" ;;
    *.pkg) echo_run xar -xvf "$1" ;;
    # Rely on GNU's tar autodetection. List of recognized suffixes:
    # https://www.gnu.org/software/tar/manual/html_node/gzip.html#auto_002dcompress
    *) echo_run tar -axvf "$1" ;;
  esac
else
  echo "'$1' can not be extracted"
fi
