#!/usr/bin/env zsh
local N=${1:-50}
local args=("$HOME/.zshrc")
start-timer "vim ${args[@]} +qall"
repeat $N { vim "${args[@]}" +qall }
end-timer $N

start-timer "vim --clean ${args[@]} +qall"
repeat $N { vim --clean "${args[@]}" +qall }
end-timer $N

start-timer "vim -u NONE ${args[@]} +qall"
repeat $N { vim -u NONE "${args[@]}" +qall }
end-timer $N
