#!/bin/sh

set -o errexit

branch=

while [ "$#" -gt 0 ]; do
  unset _arg _value
  case "$1" in
    -h | --help)
      echo "usage: $(basename "$0") [<branch>]"
      exit
      ;;
    --)
      shift
      break
      ;;
    -?*) die 1 "unknown option: ${1}" ;;
    *)
      branch="$1"
      ;;
  esac
  shift
done

if [ -n "$branch" ]; then
  # Only fetch if the branch exists on the remote
  if git ls-remote --exit-code --heads origin "$branch"; then
    echo-run git fetch origin "$branch"
  fi
  echo-run git switch "$branch"
  exit $?
fi

echo-run git fetch

# Make sure we're in a git branch
git branch >/dev/null

branch="$(git for-each-ref --sort=-committerdate --color=always refs/heads/ --format='%(HEAD) %(color:green)%(refname:short)%(color:reset) - %(contents:subject) - %(color:yellow)%(committerdate:relative)%(color:reset)' | fzf --no-multi --delimiter ' - ' --preview='git show --color=always {-1}' --ansi)"
branch="${branch%% - *}"
branch="${branch##\* }"
branch="${branch##  }"
echo-run git switch "$branch" || exit $?
git-show --quiet
