#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail
set -o xtrace

USAGE="usage: $0 > .env

Reads GitHub Codespaces secrets and outputs .env file."

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h | --help)
      echo "$USAGE" >&2
      exit
      ;;
  esac
  shift
done

if ! command -v gh &>/dev/null; then
  echo "error: the github cli (gh) must be installed" >&2
  exit 1
fi

codespace_name="$(gh codespace list --jq 'sort_by(.createdAt) | last | .name' --json createdAt,name)"

if [[ -z $codespace_name ]]; then
  echo "error: no codespaces available. create one first with 'gh cs create' or the GitHub website" >&2
  exit 1
fi

gh codespace ssh --codespace "$codespace_name" -- cat "/workspaces/.codespaces/shared/.env" |
  grep --invert-match --extended-regexp '^(CODESPACE|GITHUB_|INTERNAL|GIT_COMMITTER)'
