#!/bin/sh

USAGE="usage: $(basename "$0") [-l|--latest|-p|--pull] <branch name> [<base branch>]"

set -o errexit

branch_name=
latest=false
stash=false
base_branch=

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
    -l | --latest | -p | --pull)
      latest=true
      ;;
    --stash)
      stash=true
      ;;
    --)
      shift
      break
      ;;
    -?*)
      echo "unknown option: ${1}"
      exit 1
      ;;
    *)
      if [ -z "$branch_name" ]; then
        branch_name="$1"
      else
        base_branch="$1"
      fi
      ;;
  esac
  shift
done

if [ -z "$branch_name" ]; then
  echo-err "missing branch name" >&2
  exit 1
fi

if [ -z "$base_branch" ]; then
  base_branch="$(get-main-branch)"
fi

if $latest; then
  echo-run git fetch origin "$base_branch"
fi

stashed=false
if $stash; then
  status="$(git status --porcelain)"
  if [ -n "$status" ]; then
    stashed=true
    echo-run git stash
  fi
fi

set +o errexit
echo-run git checkout -b "$branch_name" --no-track "origin/${base_branch}"
exit_code=$?
set -o errexit

if $stashed; then
  echo-run git stash pop
fi

exit "$exit_code"
