#!/bin/sh

set -o errexit

add

merge_base="$(git merge-base "origin/HEAD" HEAD)"

# --staged is a synonym for --cached
git diff --name-only --no-ext-diff -z --cached --merge-base "$merge_base" | xargs -0 echo-run pre-commit run --files
