#!/bin/sh

if [ $# -eq 0 ]; then
  codespaces="$(gh codespace list --json name --jq '.[].name')"
  if [ "$(echo "$codespaces" | wc -l)" -eq 1 ]; then
    exec echo-run gh codespace ssh --codespace "$codespaces"
  fi
  exec echo-run gh codespace ssh
fi

case "$1" in
  create)
    if git config --get remote.origin.url >/dev/null 2>&1; then
      url="$(git config --get remote.origin.url)"
      url="${url##git@github.com:}"
      url="${url%.git}"
      case "$url" in
        :*) : ;;
        */*) set -- --repo "$url" "$@" ;;
      esac
    fi
    ;;
esac

exec echo-run gh codespace "$@"
