#!/bin/sh

set -o errexit
set -o nounset

USAGE="usage: $(basename "$0") <branch>"

branch=

while [ "$#" -gt 0 ]; do
  case "$1" in
    -[[:alnum:]][[:alnum:]]*)
      # Joined short args (e.g. -abc)
      _value="-${1##-?}"
      _arg="${1%%"${1##-?}"}"
      ;;
    --[[:alnum:]]*=*)
      # Args with values separated by an '=' character
      _value="${1#--[[:alnum:]]*=}"
      _arg="${1%%="${_value}"}"
      ;;
  esac
  if [ -n "${_arg-}${_value-}" ]; then
    shift
    set -- "$_arg" "$_value" "$@"
  fi
  unset _arg _value
  case "$1" in
    -h | --help)
      echo "$USAGE" >&2
      exit
      ;;
    --)
      shift
      break
      ;;
    -?*) die 1 "unknown option: ${1}" ;;
    *) branch="$1" ;;
  esac
  shift
done

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo-err "Not in a git repository."
  exit 128
fi

if [ -z "$branch" ]; then
  echo-err "missing branch name"
  exit 1
fi

merge_base="$(git merge-base "$branch" HEAD)"
branch_commit="$(git rev-parse "$branch")"

echo-run git cherry-pick --no-commit "${merge_base}..${branch_commit}"
