#!/bin/sh

set -o errexit

if command -v op >/dev/null 2>&1; then
  safe-run op signout --all --forget
  op_path="$(command -v op)"
  safe-run sudo rm -rf "$op_path"
else
  echo-info "Skipping since op is not installed"
fi
