#!/bin/sh

if [ "$#" -le 0 ]; then
  set -- shellcheck
fi

for file in ~/.local/bin/* ~/.shinit ~/.profile ~/.config/sh/* ~/.config/sh/*/* ~/.config/sh/*/*/*; do
  if [ ! -f "$file" ] || [ ! -r "$file" ]; then
    continue
  fi
  case $(head -1 "$file") in
    *bash*) echo-run "$@" "$file" ;;
    */sh*) echo-run "$@" "$file" ;;
    *env\ sh*) echo-run "$@" "$file" ;;
    *) continue ;;
  esac
done
