#!/usr/bin/env zsh

set -e

if ! sudo true; then
# sudo echo "$SHELL" > /dev/null
# if [[ $status -ne 0 ]]; then
  echo-info "We need sudo to do some stuff."
  return 1
fi

# sudo keep alive
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Using 'command ls' here because regular ls is aliased to add color and
# formatting.
local files=($(command ls "$HOME/.local/bin" | sort | grep update- | grep -v update-all))

local i
for i in {1..${#files}}; do
  local file="${files[$i]}"
  echo "============================================================="
  echo "Running: \033[32m${file}\033[0m (${i}/${#files})"
  echo "============================================================="
  if "$HOME/.local/bin/$file"; then
    echo-ok "${file} finished successfully"
  else
    echo-err "${file} failed with status $?"
  fi
  if [[ "$i" -lt "${#files}" ]]; then
    echo
  fi
done
