#!/bin/sh

verbose=false

for arg in "$@"; do
  case "$arg" in
    -v | --verbose) verbose=true ;;
    -h | --help)
      echo "usage: $(basename "$0") [-v|--verbose]"
      exit
      ;;
  esac
done

_files() {
  path="$1"
  find "$path" -type f -not -path '*/\.git/*' -not -name 'tags'
}

for file in $(_files ~/.local/bin) ~/.shinit ~/.profile $(_files ~/.config/sh); do
  if [ ! -f "$file" ] || [ ! -r "$file" ]; then
    continue
  fi
  case $(head -1 "$file") in
    *bash*) shellcheck "$file" ;;
    */sh*) shellcheck "$file" ;;
    *env\ sh*) shellcheck "$file" ;;
    *)
      $verbose && echo-info "Skipping ${file}"
      continue
      ;;
  esac
done
