#!/bin/sh

tag="$1"

if [ -z "$tag" ]; then
  echo "Usage: $0 TAG"
  return 1
fi

if ! in-git-repo; then
  echo-err "Not in git repository."
  return 128
fi

echo-run git fetch --tags --force --prune --quiet || return "$?"

echo-run git tag -d "$tag" || return "$?"
safe-run git push origin ":refs/tags/$tag" || return "$?"
