#!/usr/bin/env bash

if ! in-git-repo; then
  echo-err "Not in a git repository."
  exit 128
fi

head="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$head" == "HEAD" ]]; then
  echo-err "You are not on the HEAD of a branch."
  exit 1
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo-err "There are uncommitted files."
  echo-run git status
  exit 1
fi

args=("$@")

remote="$(git rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>/dev/null)"
if [[ -z "$remote" ]]; then
  args+=("--set-upstream" "origin" "$head")
fi

echo-run git push "${args[@]}"
