#!/bin/sh

set -o errexit

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "usage: $(basename "$0")"
  exit
fi

project_root="$PWD"

if git rev-parse --git-dir >/dev/null 2>&1; then
  project_root="$(git rev-parse --show-toplevel)"
fi

if [ -z "$VIRTUAL_ENV" ]; then
  if [ ! -d "${project_root}/.venv" ]; then
    echo-run python3 -m venv "${project_root}/.venv"
  fi
  echo-info "Activating venv"
  # shellcheck disable=SC1090,SC1091
  . "${project_root}/.venv/bin/activate"
fi

if [ -f "${project_root}/requirements.txt" ]; then
  echo-run pip install -r "${project_root}/requirements.txt"
else
  echo-info "No requirements.txt file."
fi
