#!/bin/sh

if ! in-git-repo; then
  echo-err "Not in a git repository."
  return 128
fi

if [ "$#" -eq 0 ]; then
  echo-run git add --verbose "$(git rev-parse --show-toplevel)"
  return "$?"
fi

echo-run git add --verbose "$@"
