#!/usr/bin/env zsh

set -e

if command -v tmux &>/dev/null; then
  echo-info "Installing tmux terminfo file"
  echo-run tic -x "${HOME}/.config/tmux/tmux.terminfo"
else
  echo-warn "tmux not installed."
fi
