#!/usr/bin/env zsh

set -e

sudo echo "$SHELL" > /dev/null
if [[ $status -ne 0 ]]; then
  echo-info "We need sudo to do some stuff"
  return 1
fi

# Using 'command ls' here because regular ls is aliased to add color and
# formatting.
local files=($(command ls "$HOME/.local/bin" | sort | grep bootstrap-))

local i
for i in {1..${#files}}; do
  local file="${files[$i]}"
  echo "============================================================="
  echo "Running: ${fg[green]}${file}${reset_color} (${i}/${#files})"
  echo "============================================================="
  "$HOME/.local/bin/$file"
  [[ "$i" -lt "${#files}" ]] && echo
done
