#!/bin/sh

set -o errexit

USAGE="usage: $(basename "$0") [--verbose] <version>"

if [ $# -le 0 ]; then
  echo "$USAGE"
  exit 1
fi

verbose=false
version=

while [ $# -gt 0 ]; do
  case "$1" in
    -h | --help)
      echo "$USAGE"
      exit
      ;;
    --verbose)
      verbose=true;
      ;;
    *.*.*)
      version="$1"
      ;;
    *)
      echo-err "unknown argument: ${1}"
      exit 1
      ;;
  esac
  shift
done

if [ -z "$version" ]; then
  echo-err "A version is required"
  exit 1
fi

set --
if $verbose; then
  set -- "$@" --verbose
fi

openssl_path="$(brew --prefix openssl)"
sdk_path="$(xcrun --show-sdk-path)"

case "$version" in
  3.8.* | 3.9.*)
    echo-run command pyenv install "$@" "$version"
    exit $?
    ;;
  *)
    # https://github.com/pyenv/pyenv/wiki/Common-build-problems
    # CFLAGS: "You can set your CFLAGS to accepted safe values to help get a little
    # more speed."
    echo-info "Running pyenv with a bunch of extra flags to make things work" >&2
    SYSTEM_VERSION_COMPAT=1 \
      CFLAGS="${CFLAGS} -I${sdk_path}/usr/include -I${openssl_path}/include" \
      LDFLAGS="${LDFLAGS} -L${sdk_path}/usr/lib -L${openssl_path}/lib" \
      echo-run command pyenv install "$@" "$version"
    exit $?
    ;;
esac
