#!/usr/bin/env zsh

local port="${1:-8000}"

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "usage: $(basename "$0") [PORT]"
  return 1
fi

( sleep 2; open "http://127.0.0.1:${port}" ) &
echo-run python3 -m http.server "$port" --bind 127.0.0.1 || return "$?"
