#!/bin/sh

bin="${1:-${HOME}/.local/bin}"

for file in "$bin"/*; do
  case $(head -1 "$file") in
    *bash*) echo-run shellcheck "$file";;
    */sh*) echo-run shellcheck "$file";;
    *env\ sh*) echo-run shellcheck "$file";;
    *) continue;;
  esac
done
