#!/bin/sh

set -o errexit

if ! in-git-repo; then
  echo-err "Not in a git repository."
  return 128
fi

printf "Getting remote HEAD... "
GIT_HEAD="$(get-remote-head)"
echo "$GIT_HEAD"

echo-run git checkout --quiet "$GIT_HEAD"
echo-run git pull --quiet --rebase --no-tags --prune origin "$GIT_HEAD"
git-show --quiet
