#!/usr/bin/env zsh

json=''

if [ -p /dev/stdin ]; then
  while read line; do
    json+="$line\n"
  done
  json+="$line"
else
  json="$*"
fi

local from_clipboard
if [[ -z "$json" ]]; then
  json="$(pbpaste)"
  from_clipboard=1
fi

if [[ -z "$json" ]]; then
  exit
fi

for key value in $(echo "$json" | jq --raw-output 'to_entries | .[] | [.key, .value] | @sh'); do
  key="${key%\'}"
  value="${value%\'}"
  key="${key#\'}"
  value="${value#\'}"
  printf "--%s=%s " "${key//_/-}" "$value"
done
echo
