#!/usr/bin/env zsh

set -e
source "$HOME/.zshrc"

if whence snowsql >/dev/null; then
  echo-info 'Skipping snowsql because it is already installed.'
  return
fi

local tmpdir="$(mktemp -d)"
echo-run cd "$tmpdir"

echo-run curl -O 'https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/darwin_x86_64/snowsql-1.2.7-darwin_x86_64.pkg'

echo-run installer -pkg 'snowsql-1.2.7-darwin_x86_64.pkg' -target CurrentUserHomeDirectory

echo-run ln -s "$HOME/Applications/SnowSQL.app/Contents/MacOS/snowsql" '/usr/local/bin/snowsql'

echo-info "Cleaning up temporary directory."
echo-run rm -rf "$tmpdir"
