#!/usr/bin/env bash

if ! in-git-repo; then
  echo-err "Not in a git repository."
  exit 128
fi

if [[ "$1" == "" ]]; then
  echo-info -n "Getting remote HEAD... "
  GIT_HEAD="$(get-remote-head)"
  echo "$GIT_HEAD"

  echo-run git fetch --quiet --no-tags origin "$GIT_HEAD" && \
  echo-run git rebase --autostash origin/"$GIT_HEAD"
  exit $?
fi

if [[ ("$1" == "-i" || "$1" == "--interactive") && "$#" -le 1 ]]; then
  echo-info -n "Getting remote HEAD... "
  GIT_HEAD="$(get-remote-head)"
  echo "$GIT_HEAD"

  echo-run git fetch --quiet --no-tags origin "$GIT_HEAD" && \
  echo-run git rebase --interactive --autostash origin/"$GIT_HEAD"
  exit $?
fi

if [[ "$1" == "--continue" && "$#" -le 1 ]]; then
  echo-run git rebase --continue
  exit $?
fi

if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
  echo "Usage: $0 [<git rebase args>]"
  exit
fi

echo-run git fetch --quiet && \
echo-run git rebase "$@"
