#!/bin/bash

charset=({a..z})
permute(){
  (($1 == 0)) && { echo "$2"; return; }
  for char in "${charset[@]}"
  do
    permute "$((${1} - 1 ))" "$2$char"
  done
}
permute "$1" | xargs -n 1 -P 4 is-domain-available
