#!/bin/sh

set -e

terminfo_file="$(mktemp)"
echo-eval "curl --silent https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info > $terminfo_file"
echo-run tic -xe alacritty,alacritty-direct "$terminfo_file"
echo-run rm "$terminfo_file"

echo-eval "curl --silent https://raw.githubusercontent.com/alacritty/alacritty/master/extra/completions/_alacritty > ${HOME}/.config/zsh/_alacritty"
