#!/bin/sh

set -o errexit

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "usage: $(basename "$0") [commit message]"
fi

if [ "$#" -gt 1 ]; then
  echo-err 'unsupported number of arguments'
fi

add

if [ "$#" -eq 1 ]; then
  echo-run git commit -m "$1"
else
  echo-run git commit
fi
