#!/bin/sh

set -o errexit

if [ $# -gt 0 ]; then
  echo-run arc work "$@"
  exit $?
fi

diff_id="$(arc list --ansi | fzf --ansi | grep --no-filename --only-matching 'D\d\d*')"

if [ -z "$diff_id" ]; then
  exit $?
fi

echo-run arc work "$diff_id"
