#!/bin/sh

usage="Wrapper for chezmoi.

Usage:
  $(basename "$0") -h | --help            Show usage and exit.
  $(basename "$0") apply                  Show a diff and apply changes.
  $(basename "$0") <any chezmoi command>  Passthrough to chezmoi.
"

command="$1"
if [ -z "$command" ]; then
  echo "$usage"
  return 1
fi

shift

case "$command" in
  -h | --help)
    echo "$usage"
    return
    ;;
  apply)
    if echo-run chezmoi verify; then
      echo-info "Nothing to apply."
      return
    fi
    if ! echo-run chezmoi diff --no-pager; then
      echo-warn "Error showing diff. Are you signed in to 1Password?"
      return 1
    fi
    if ! safe-run chezmoi apply; then
      echo-info "You can run 'dotfiles add <file>...' to update the source."
      return
    fi
    ;;
  *)
    echo-run chezmoi "$command" "$@"
    ;;
esac
