#!/bin/sh

for file in "$HOME"/.local/bin/*; do
  case $(head -1 "$file") in
    *bash*) echo-run shellcheck "$file";;
    */sh*) echo-run shellcheck "$file";;
    *env\ sh*) echo-run shellcheck "$file";;
    *) continue;;
  esac
done
