#!/bin/bash
# Usage: errcolor <command> [<args...>]
#
# Run command, color its stderr stream in red and print its exit code.
set -eu

if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" == "--help" ]; then
  echo "usage: $(basename "$0") <command> [<args...>]"
  exit
fi

status=0
"$@" 2> >(
  IFS=$'\n'
  while read -r line; do
    printf "\e[0;31m%s\e[m\n" "$line"
  done
) || status=$?
printf "\e[0;33mexit code: %d\e[m\n" $status
