"$schema" = 'https://starship.rs/config-schema.json'
format = '$hostname$directory$git_branch${custom.git_host}$git_commit$git_state$nodejs$time$cmd_duration$status${custom.stashes}$shell$line_break$shlvl${custom.container}$jobs$character'
add_newline = false
command_timeout = 2000

[hostname]
disabled = true
ssh_symbol = ''

[cmd_duration]
min_time = 0
show_milliseconds = true

[directory]
fish_style_pwd_dir_length = 2
read_only = '!'
read_only_style = 'bold red'
repo_root_style = 'bold bright-blue'

[status]
format = '[ $status( $signal_name) ]($style) '
disabled = false
style = 'fg:white bg:red bold'

[git_branch]
symbol = ''

[git_status]
disabled = true

[nodejs]
symbol = ''

[time]
disabled = false
use_12hr = true
time_format = '%I:%M %P'

[custom.container]
shell = ['dash', '-eu']
when = 'test -f /.dockerenv || grep -q docker /proc/1/cgroup'
style = 'bold fg:purple'
command = 'echo 🐳'
description = 'Identifies that we are in a container'

[custom.git_host]
shell = ['dash', '-eu']
command = 'command git ls-remote --get-url'
when = 'command git rev-parse --is-inside-work-tree'
format = 'at [$output]($style) '
disabled = true

[custom.stashes]
shell = ['dash', '-eu']
command = '''
# Basically copied from:
# https://github.com/git/git/blob/30cc8d0f147546d4dd77bf497f4dec51e7265bd8/builtin/stash.c#L791
stash_count="$(git rev-list --walk-reflogs --first-parent --count refs/stash --)"
if [ "$stash_count" -eq 1 ]; then
  echo "${stash_count} stash"
else
  echo "${stash_count} stashes"
fi
'''
when = 'git rev-parse --verify refs/stash'
format = '[$output]($style) '
style = 'fg:red bold'

[jobs]
symbol = '+'
style = 'fg:red bold'

[shell]
disabled = false
bash_indicator = 'bash'
fish_indicator = 'fish'

[shlvl]
disabled = false
symbol = ''
style = 'green'
threshold = 0
