name: CI

on:
  push:

jobs:
  dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: georgewitteman/gitpod-dotfiles-base:latest

      - name: Install dotfiles to test
        run: docker run --rm georgewitteman/gitpod-dotfiles-base:latest sh -c 'CI=true sh -c "$(curl -fsLS git.io/chezmoi)" -- init --apply georgewitteman'

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: georgewitteman/gitpod-dotfiles-base:latest
          # build on feature branches, push only on master branch
          push: ${{ github.ref == 'refs/heads/master' }}

  dev-container-builds:
    runs-on: ubuntu-latest
    concurrency:
      group: dev-containers-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: .docker/dev-alpine.Dockerfile
          tags: georgewitteman/dev-alpine:latest
          # build on feature branches, push only on master branch
          push: ${{ github.ref == 'refs/heads/master' }}

  clone-and-install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Uninstall homebrew
        if: ${{ matrix.os == 'macOS-latest' }}
        run: 'sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" -- --force'
      - run: rm -rf ~/.nvm
      - run: ./install.sh

  codespaces:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v3
      - run: ./install.sh

  docker:
    strategy:
      fail-fast: false
      matrix:
        image: ["ubuntu:18.04", "ubuntu:20.04"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - run: apt update
      - run: apt install --yes curl openssh-client unzip gnupg vim git
      - name: CVE-2022-24765 workaround (https://github.com/actions/checkout/issues/760)
        run: git config --global --add safe.directory /__w/dotfiles/dotfiles
      - uses: actions/checkout@v3
      - run: ./install.sh
      - run: ls -la $HOME

  docker-alpine:
    strategy:
      fail-fast: false
      matrix:
        image: ["alpine:latest"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - run: apk --update --upgrade add git
      - name: CVE-2022-24765 workaround (https://github.com/actions/checkout/issues/760)
        run: git config --global --add safe.directory /__w/dotfiles/dotfiles
      - uses: actions/checkout@v3
      - run: ./install.sh
      - run: ls -la $HOME

  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: 'sudo apt update; sudo apt install --yes shellcheck'
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: 'curl -sS https://webinstall.dev/shfmt | bash'
      - if: ${{ matrix.os == 'macOS-latest' }}
        run: 'brew install shellcheck shfmt'
      - run: rm -rf ~/.nvm
      - run: ./install.sh
      - run: "${HOME}/.bin/shfmt-check-all --verbose --debug"
      - run: "${HOME}/.bin/shellcheck-all --verbose --debug"
