name: Continuous integration

on: [push]

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail

      - uses: actions/checkout@v2

      - name: Install
        run: |
          sh -c "$(curl -fsLS git.io/chezmoi)"
          if [ -n "$GITHUB_PATH" ]; then
            echo Adding ${BINDIR} to ${GITHUB_PATH}
            echo $BINDIR >> "$GITHUB_PATH"
          else
            echo ::add-path::${BINDIR}
          fi
        env:
          BINDIR: ${HOME}/.chezmoi_bin
      - name: Copy repository to chezmoi
        run: |
          rm -rf "$(chezmoi source-path)"
          mkdir -p "$(dirname $(chezmoi source-path))"
          cp -r "$GITHUB_WORKSPACE" "$(chezmoi source-path)"

      - name: Get date for cache key
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - name: Cache Homebrew downloads
        if: ${{ runner.os == 'macOS' && !env.ACT }}
        uses: actions/cache@v2
        with:
          key: homebrew-cache-${{ runner.os }}-${{ steps.get-date.outputs.date }}
          path: ~/Library/Caches/Homebrew
          restore-keys: homebrew-cache-${{ runner.os }}-
      - name: Cache pyenv builds
        if: ${{ !env.ACT }}
        uses: actions/cache@v2
        with:
          key: pyenv${{ runner.os }}-${{ steps.get-date.outputs.date }}
          path: ~/.local/share/pyenv
          restore-keys: pyenv${{ runner.os }}-

      - name: Init and apply
        run: |
          chezmoi init --no-tty
          chezmoi apply --no-tty
        env:
          GIT_SSH_COMMAND: ssh -i ${{ env.HOME }}/.ssh/id_ed25519 -o "UserKnownHostsFile ${{ env.HOME }}/.ssh/known_hosts"

      - name: Install shellcheck
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get --quiet --quiet --yes update
          sudo apt-get --quiet --quiet --yes install shellcheck
      - name: Shellcheck
        run: 'sh -l -c "shellcheck-all"'
