name: Continuous integration

on: [push]

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail
      - name: Cache Homebrew downloads
        uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          key: homebrew-cache-${{ hashFiles('~/Library/Caches/Homebrew/**') }}
          path: ~/Library/Caches/Homebrew
          restore-keys: homebrew-cache-
      - name: Cache pyenv builds
        uses: actions/cache@v2
        with:
          key: pyenv-cache-${{ hashFiles('~/.local/share/pyenv/cache/**') }}
          path: ~/.local/share/pyenv/cache
          restore-keys: pyenv-cache-
      - name: Install, init, and apply
        run: 'sh -c "$(curl -fsLS git.io/chezmoi)" -- init --depth=1 --apply georgewitteman'
      - name: Shellcheck
        run: 'sh -l -c "shellcheck-all"'
