name: Continuous integration

on: [push]

jobs:
  test_new_install:
    runs-on: macos-latest
    steps:
      - name: Install, init, and apply
        shell: bash
        run: 'PATH="${PATH}:${HOME}/.local/bin" sh -c "$(curl -fsLS git.io/chezmoi)" -- init --depth=1 --apply --verbose georgewitteman'
