name: CI

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - runs: ./install.sh

  codespaces:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh
