name: CI

on:
  push:
  pull_request:

jobs:
  scripts:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - runs: ./install.sh
