name: Continuous integration

on: [push]

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail
      - name: Cache Homebrew downloads
        uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          key: homebrew-cache-${{ runner.os }}-${{ github.sha }}
          path: ~/Library/Caches/Homebrew
          restore-keys: homebrew-cache-${{ runner.os }}
      - name: Cache pyenv builds
        uses: actions/cache@v2
        with:
          key: pyenv-cache-${{ runner.os }}-${{ github.sha }}
          path: ~/.local/share/pyenv/cache
          restore-keys: pyenv-cache-${{ runner.os }}

      - name: Install
        run: |
          sh -c "$(curl -fsLS git.io/chezmoi)"
          echo $BINDIR >> "$GITHUB_PATH"
        env:
          BINDIR: ${HOME}/.chezmoi_bin

      - name: Checkout
        run: |
          set -x
          chezmoi init --depth=1 "$GITHUB_REPOSITORY"
          git -C $(chezmoi source-path) fetch origin "$GITHUB_SHA"
          git -C $(chezmoi source-path) checkout "$GITHUB_SHA"
          set +x
      - name: Init and apply
        run: |
          chezmoi init
          chezmoi apply

      - name: Shellcheck
        run: 'sh -l -c "shellcheck-all"'
