name: CI

on:
  push:
  pull_request:
  schedule:
    # 5am PT daily
    - cron: '30 12 * * *'

jobs:
  scripts:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail

      - uses: actions/checkout@v2
      - uses: ./.github/actions/chezmoi

      - name: Get date for cache key
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - name: Cache Homebrew downloads
        if: ${{ runner.os == 'macOS' && !env.ACT }}
        uses: actions/cache@v2
        with:
          key: homebrew-cache-${{ matrix.os }}-${{ steps.get-date.outputs.date }}
          path: ~/Library/Caches/Homebrew
          restore-keys: |
            homebrew-cache-${{ matrix.os }}-
            homebrew-cache-${{ runner.os }}-
      - name: Cache pyenv builds
        if: ${{ !env.ACT }}
        uses: actions/cache@v2
        with:
          key: pyenv-${{ matrix.os }}-${{ steps.get-date.outputs.date }}
          path: ~/.local/share/pyenv/cache
          restore-keys: |
            pyenv-${{ matrix.os }}-
            pyenv-${{ runner.os }}-

      - run: chezmoi apply --no-tty
        env:
          GIT_SSH_COMMAND: ssh -i ${HOME}/.ssh/id_ed25519 -o "UserKnownHostsFile ${HOME}/.ssh/known_hosts"
