name: misspell

on:
  push:
    branches: [main]
  pull_request:

jobs:
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-misspell@v1
        with:
          locale: US
          filter_mode: nofilter
          fail_on_error: true
