name: Quick Install

on:
  push:
    branches:
      - main
  schedule:
    # 5am PT daily
    - cron: '30 12 * * *'

jobs:
  macos:
    runs-on: macos-12
    steps:
      - run: rm -rf ~/.nvm ~/.pyenv
      - name: Uninstall homebrew
        run: 'sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" -- --force'
      - run: 'curl -fsSL "https://get.chezmoi.io" | sh -s -- -b ~/.local/bin -d init -a georgewitteman'

  codespaces:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/javascript-node
      env:
        CODESPACES: true
    steps:
      - run: 'curl -fsSL "https://get.chezmoi.io" | sh -s -- -b ~/.local/bin -d init -a georgewitteman'
